# Generated by Django 5.2.16 on 2026-08-28 21:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of raw 32-char URL-safe token; raw token NEVER stored",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Filled by BOT on /start login_<token>",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Token creation timestamp"
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="+5 min from creation")),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Filled by WEB on login completion",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "login_tokens",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Optional public @username; NOT used for t.me link or publishing",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram user ID; required for authentication (nullified on GDPR withdrawal)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Stable Telegram chat ID; set on first bot contact, never nullified",
                        unique=True,
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False, help_text="Account is blocked from posting"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "is_declined",
                    models.BooleanField(
                        default=False,
                        help_text="User declined consent (browse-only mode)",
                    ),
                ),
                (
                    "ads_auto_publish",
                    models.BooleanField(
                        default=True,
                        help_text="Publishing ban - when False, ads go to DRAFT instead of ON_MODERATION",
                    ),
                ),
                (
                    "telegram_premium",
                    models.BooleanField(
                        default=False,
                        help_text="User has Telegram Premium subscription",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
                (
                    "consent_given_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="GDPR consent given timestamp (US-A8 / decision F)",
                        null=True,
                    ),
                ),
                (
                    "consent_revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="GDPR consent revoked timestamp",
                        null=True,
                    ),
                ),
                (
                    "telegram_language",
                    models.CharField(
                        choices=[("ru", "ru"), ("bs", "bs"), ("en", "en")],
                        default="ru",
                        help_text="Telegram-reported language code for localized bot messages",
                        max_length=5,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[("telegram", "telegram"), ("seed", "seed")],
                        db_index=True,
                        default=None,
                        help_text="Origin of record (null = real user, 'seed' = seed-generated)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "preferred_city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Buyer's preferred city for default catalog/search filtering (nullable; SET_NULL on city removal)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.city",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="users",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key identifying an anonymous consent action",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "consent_given_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the consent action"
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0",
                        help_text="Banner text version shown to the user",
                        max_length=20,
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("accepted", "accepted"),
                            ("declined", "declined"),
                            ("withdrawn", "withdrawn"),
                        ],
                        help_text="Consent choice made by the user",
                        max_length=20,
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=dict,
                        help_text="Granular category flags (CookieCategory -> bool)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Anonymized IP (last IPv4 octet zeroed)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Truncated User-Agent header from the consent request",
                        max_length=500,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who acted (null for anonymous cookie-based consent)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "consent_records",
                "ordering": ["-consent_given_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["consent_revoked_at"], name="IX_users_erasure_sweep"
            ),
        ),
    ]
