# Generated by Django 5.2.16 on 2026-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Anonymized IP (IPv4 last octet zeroed; IPv6 /64 prefix retained)', null=True),
        ),
    ]
