# Generated by Django 5.2.16 on 2026-08-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0002_alter_user_telegram_id_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_city',
            field=models.ForeignKey(blank=True, help_text="Buyer's preferred city for default catalog/search filtering (nullable; SET_NULL on city removal)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.city'),
        ),
    ]
