# Generated by Django 5.2.16 on 2026-08-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_preferred_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key identifying an anonymous consent action', max_length=40, null=True)),
                ('consent_given_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the consent action')),
                ('consent_version', models.CharField(default='1.0', help_text='Banner text version shown to the user', max_length=20)),
                ('choice', models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('withdrawn', 'withdrawn')], help_text='Consent choice made by the user', max_length=20)),
                ('categories', models.JSONField(default=dict, help_text='Granular category flags (CookieCategory -> bool)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Anonymized IP (last IPv4 octet zeroed)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Truncated User-Agent header from the consent request', max_length=500)),
                ('user', models.ForeignKey(blank=True, help_text='User who acted (null for anonymous cookie-based consent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_records',
                'ordering': ['-consent_given_at'],
            },
        ),
    ]
