# Generated by Django 5.2.17 on 2026-10-04 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Record who initiated each consent action and by what mechanism (06-NEW-02).

    Two ``AddField``s plus one help_text-only ``AlterField`` on ``user`` (Django
    tracks ``help_text``; the correction is mandated by the block and the
    ``AlterField`` is what keeps ``makemigrations --check`` clean — it changes no
    DDL). No ``RunPython`` and no backfill: the ledger never recorded the actor,
    so nothing is derivable. ``AddField`` writes the default, so every
    pre-existing row reads ``action_source = "unknown"`` with ``initiated_by =
    NULL``; that means "written before the actor was recorded; the mechanism was
    never captured and is not recoverable", and carries no inference about who
    acted. Reversible, but the reversal is LOSSY: it destroys every actor and
    mechanism value written and re-applying re-stamps pre-existing rows.
    """

    dependencies = [
        ("users", "0004_consentrecord_sweep_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="action_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self_service", "self_service"),
                    ("anonymous_web", "anonymous_web"),
                    ("admin_staff", "admin_staff"),
                    ("system", "system"),
                    ("unknown", "unknown"),
                ],
                db_index=True,
                default="unknown",
                help_text=(
                    "Mechanism that initiated the action (06-NEW-02). UNKNOWN is "
                    "the default and means the row predates this column: the "
                    "mechanism was never captured and is not recoverable. No row "
                    "written through the recording service carries UNKNOWN."
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Acting account, recorded ONLY when it is not the subject "
                    "(06-NEW-02). NULL means no acting account distinct from the "
                    "subject — a self-service action, an anonymous visitor, or a "
                    "system action; action_source tells those apart. Never "
                    "CASCADE: consent_hard_delete deletes User rows and a "
                    "cascade would destroy the Art. 7(1) ledger. Retained to the "
                    "decision bound (5 years), not the 90-day fingerprint bound "
                    "— see the open owner/DPO question."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The subject of the consent action (null for anonymous "
                    "cookie-based consent). This is NOT the actor — a third-party "
                    "actor is recorded only in initiated_by (06-NEW-02)."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
