# Generated by Django 5.2.17 on 2026-10-04 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the documented legal-hold marker to the consent ledger (06-NEW-02).

    One ``AddField`` with ``default=False`` and ``null=False``. The default
    leaves every existing row un-held, so there is **no backfill and no data
    migration** — ``AddField`` writes the default to pre-existing rows. No
    ``RunPython`` and no index change: the state "the actor was cleared at the
    12-month window" is derivable from ``action_source`` plus the row's age, so
    no second marker column (such as ``actor_anonymised_at``) is added.

    One help_text-only ``AlterField`` on ``initiated_by`` (Django tracks
    ``help_text``; the retention-wording correction is mandated by BLOCK 19 and
    this ``AlterField`` is what keeps ``makemigrations --check`` clean — it
    changes no DDL). Reversible: reversing drops ``legal_hold`` and its hold
    flags, and restores the prior ``initiated_by`` help_text.
    """

    dependencies = [
        ("users", "0005_consentrecord_initiated_by_action_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="legal_hold",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Documented legal hold (06-NEW-02). Default False leaves "
                    "every existing row un-held, so no backfill is needed. A hold "
                    "suspends the 12-month actor erasure ONLY: it never restores "
                    "what the 90-day fingerprint window already cleared, and it "
                    "never extends the decision fields, which are "
                    "anonymised-but-never-deleted at every age. "
                    "Superuser-settable (exemption from erasure, not evidence)."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Acting account, recorded ONLY when it is not the subject "
                    "(06-NEW-02). NULL means either no acting account distinct "
                    "from the subject — a self-service action, an anonymous "
                    "visitor, or a system action — or an admin_staff attribution "
                    "cleared after 12 months (unless held) or emptied by SET_NULL "
                    "when the acting account was hard-deleted; action_source "
                    "tells those apart. Never CASCADE: consent_hard_delete "
                    "deletes User rows and a cascade would destroy the Art. 7(1) "
                    "ledger. The acting account is irreversibly anonymised 12 "
                    "months after the action — a chosen minimisation period "
                    "justified by purpose, NOT a statutory term, and deliberately "
                    "shorter than the 5-year decision bound which governs the "
                    "decision fields only. A documented legal_hold suspends this "
                    "actor erasure."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
