# Generated by Django 5.2.16 on 2026-08-22

from django.db import migrations, models


def seed_initial_rates(apps, schema_editor):
    """Seed the fixed initial exchange rates (PO-05).

    EUR is the base currency (rate 1.0). BAM ≈ 0.512 and RSD ≈ 0.0105 are
    fixed seed values that will be replaced when auto-update from an official
    source is implemented. Source label ``manual_seed``, all ``is_current``.
    """
    ExchangeRate = apps.get_model("currencies", "ExchangeRate")
    rates = [
        {"currency": "EUR", "rate_to_eur": "1.0", "source": "manual_seed"},
        {"currency": "BAM", "rate_to_eur": "0.512", "source": "manual_seed"},
        {"currency": "RSD", "rate_to_eur": "0.0105", "source": "manual_seed"},
    ]
    for rate in rates:
        ExchangeRate.objects.update_or_create(
            currency=rate["currency"],
            defaults={
                "rate_to_eur": rate["rate_to_eur"],
                "effective_date": "2026-08-22",
                "source": rate["source"],
                "is_current": True,
            },
        )


def remove_initial_rates(apps, schema_editor):
    """Reverse: drop the seeded rates."""
    ExchangeRate = apps.get_model("currencies", "ExchangeRate")
    ExchangeRate.objects.filter(source="manual_seed").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR"),
                            ("RSD", "RSD"),
                            ("BAM", "BAM"),
                        ],
                        help_text="Currency this rate applies to (ISO 4217 code)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "rate_to_eur",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Number of EUR equal to one unit of this currency (EUR base = 1.0)",
                        max_digits=14,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date this rate takes effect (audit trail for rate changes)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Origin of the rate, e.g. 'manual_seed' or an official provider",
                        max_length=50,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Only current rows (one per currency) are used for normalization",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "exchange_rates",
            },
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("currency", "is_current"),
                name="uq_exchange_rate_current_per_currency",
            ),
        ),
        migrations.RunPython(seed_initial_rates, remove_initial_rates),
    ]
