# Generated by Django 5.2.16 on 2026-08-03 21:32

import apps.core.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_min_length', models.PositiveIntegerField(default=5, help_text='Minimum title length in characters')),
                ('title_max_length', models.PositiveIntegerField(default=100, help_text='Maximum title length in characters')),
                ('description_min_length', models.PositiveIntegerField(default=10, help_text='Minimum description length in characters')),
                ('description_max_length', models.PositiveIntegerField(default=2000, help_text='Maximum description length in characters')),
                ('price_required', models.BooleanField(default=True, help_text='If True, price field is required for all ads')),
                ('min_images', models.PositiveIntegerField(default=1, help_text='Minimum number of images required')),
                ('max_images', models.PositiveIntegerField(default=5, help_text='Maximum number of images allowed')),
                ('banned_words', models.JSONField(blank=True, default=list, help_text='List of banned words for moderation (case-insensitive)')),
                ('max_ads_per_user', models.PositiveIntegerField(default=10, help_text='Maximum active ads per user')),
                ('duplicate_title_threshold', models.PositiveIntegerField(default=85, help_text='Percentage similarity threshold for duplicate title detection (0-100)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Moderation Criteria',
                'verbose_name_plural': 'Moderation Criteria',
                'db_table': 'moderation_criteria',
            },
        ),
        migrations.CreateModel(
            name='ModeratorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reject', 'reject'), ('ban_account', 'ban_account'), ('soft_delete', 'soft_delete'), ('criteria_change', 'criteria_change'), ('other', 'other')], help_text='Type of moderator action', max_length=20)),
                ('reason', models.TextField(help_text='Moderation reason (INTERNAL ONLY - never shown to seller)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Action timestamp')),
            ],
            options={
                'db_table': 'moderation_action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdModerationPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.PositiveSmallIntegerField(default=0)),
                ('priority_level', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default=apps.core.enums.AdPriorityLevel['MEDIUM'], max_length=10)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('escalation_required', models.BooleanField(default=False)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_priority', to='ads.ad')),
            ],
            options={
                'db_table': 'ad_moderation_priorities',
            },
        ),
    ]
