# Generated by Django 5.2.16 on 2026-08-03 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationcriteria',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who last updated criteria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderatoractionlog',
            name='ad',
            field=models.ForeignKey(blank=True, help_text='Ad being moderated (SET NULL on deletion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='ads.ad'),
        ),
        migrations.AddField(
            model_name='moderatoractionlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who was moderated or performed action (SET NULL on erasure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admoderationpriority',
            index=models.Index(fields=['priority_level'], name='ad_moderati_priorit_dec75a_idx'),
        ),
        migrations.AddIndex(
            model_name='admoderationpriority',
            index=models.Index(fields=['base_score'], name='ad_moderati_base_sc_bb70a8_idx'),
        ),
        migrations.AddIndex(
            model_name='admoderationpriority',
            index=models.Index(fields=['escalation_required'], name='ad_moderati_escalat_6731b8_idx'),
        ),
    ]
