# Generated by Django 5.2.17 on 2026-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatoractionlog',
            name='reason',
            field=models.TextField(help_text="Moderation reason (INTERNAL ONLY - never shown to seller). Do not paste a seller's contact details: phone numbers, e-mail addresses and personal names are masked when this row is written, and the masking is irreversible. The text is never shortened."),
        ),
    ]
