# Generated by Django 5.2.16 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaDeletionError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_key",
                    models.TextField(
                        help_text="Storage key (UUID-based, no PII) of the file that could not be deleted"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        help_text="Exception class name (e.g. PermissionError)",
                        max_length=120,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        help_text="Truncated exception message", max_length=1000
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        help_text="Number of deletion attempts made before giving up"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the deletion failure was recorded",
                    ),
                ),
            ],
            options={
                "db_table": "media_deletion_errors",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="idx_media_del_err_created"
                    ),
                    models.Index(fields=["error_type"], name="idx_media_del_err_type"),
                ],
            },
        ),
    ]
