"""Create the IX_users_erasure_sweep partial index.

The ads lifecycle indexes (IX_ads_archive_sweep, IX_ads_delete_sweep) are
now auto-generated by Django in ads migration 0002. This migration creates
the user-side erasure sweep index only.

Uses CREATE INDEX IF NOT EXISTS (PostgreSQL 18+) for idempotency.
"""

from django.db import migrations


class Migration(migrations.Migration):
    """Create the user erasure sweep index if absent."""

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS IX_users_erasure_sweep
                ON users (consent_revoked_at);
            """,
            reverse_sql="DROP INDEX IF EXISTS IX_users_erasure_sweep;",
        ),
    ]