# Generated by Django 5.2.16 on 2026-09-03

from django.db import migrations


def seed_site_config(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.get_or_create(pk=1, defaults={"name": "Bazuna"})


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_site_config, reverse_code=migrations.RunPython.noop),
    ]
