# Generated by Django 5.2.17 on 2026-09-25 21:08

import apps.core.enums
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_bot_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('email', 'email'), ('telegram', 'telegram')], help_text='Channel type: email or telegram', max_length=10)),
                ('label', models.CharField(help_text='Human-readable label for this support contact', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address (required when channel_type is email)', max_length=254, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Telegram user/channel ID (required when channel_type is telegram)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this support contact is currently offered')),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower sorts first)')),
            ],
            options={
                'verbose_name': 'Support Contact',
                'verbose_name_plural': 'Support Contacts',
                'db_table': 'support_contacts',
                'ordering': ['ordering', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('channel_type', apps.core.enums.SupportChannelType['EMAIL']), ('email__isnull', False), ('telegram_id__isnull', True)), models.Q(('channel_type', apps.core.enums.SupportChannelType['TELEGRAM']), ('email__isnull', True), ('telegram_id__isnull', False)), _connector='OR'), name='support_contact_channel_value_required')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat_id for anonymous attribution')),
                ('telegram_id', models.BigIntegerField(help_text="User's Telegram ID")),
                ('username', models.CharField(blank=True, help_text='Telegram username (if available)', max_length=255, null=True)),
                ('text', models.TextField(help_text='Ticket body / message text')),
                ('status', models.CharField(choices=[('open', 'open'), ('replied', 'replied'), ('closed', 'closed')], default=apps.core.enums.SupportTicketStatus['OPEN'], help_text='Current lifecycle status of the ticket', max_length=10)),
                ('ticket_ref', models.CharField(editable=False, help_text='Human-readable reference: SUP-YYYYMM-NNN', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the ticket was created')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who opened the ticket (null if anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
