# Generated by Django 5.2.17 on 2026-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_support_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerDailyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_daily', models.DateField(blank=True, help_text='Calendar date the daily set last completed cleanly', null=True)),
                ('last_daily_completed_at', models.DateTimeField(blank=True, help_text='When the daily set last completed cleanly', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this marker row was last written')),
            ],
            options={
                'verbose_name': 'Scheduler Daily State',
                'verbose_name_plural': 'Scheduler Daily State',
                'db_table': 'scheduler_daily_state',
            },
        ),
    ]
