# Generated by Django 5.2.17 on 2026-10-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduler_daily_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who opened the ticket (null if unattributed). Deleted with the user (06-PII-101): nothing is derived from a ticket.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
