"""Tests for the squash_rehydrate_runsql management command.

Verifies injection of ``migrations.RunSQL`` trigger DDL into a freshly
squashed ``ads/0001_initial.py``: dry-run leaves the file untouched, a real
run splices valid ``RunSQL`` operations before the closing ``]`` of
``operations``, the result re-parses as valid Python, injection is idempotent,
and a missing migration is reported gracefully.

The command writes to ``apps.get_app_config("ads").path / migrations /
0001_initial.py``. Tests redirect that path to a temp copy so the real
production migration is never modified.
"""

import ast
import pathlib
from io import StringIO
from types import SimpleNamespace

import pytest
from django.apps import apps as django_apps
from django.core.management import call_command

from apps.ads.management.commands.setup_search_triggers import DDL_STATEMENTS
from apps.core.management.commands import squash_rehydrate_runsql as cmd_module
from apps.core.management.commands.squash_rehydrate_runsql import MARKER

pytestmark = [pytest.mark.unit]


# Minimal, self-contained stand-in for a regenerated squashed migration file.
_FAKE_MIGRATION = """\
#
# Generated by Django
#
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
"""


def _write_fake_migration(tmp_path: pathlib.Path) -> pathlib.Path:
    """Create a marker-free fake migration under tmp_path/migrations/."""
    migrations_dir = tmp_path / "migrations"
    migrations_dir.mkdir(parents=True)
    migration_path = migrations_dir / "0001_initial.py"
    migration_path.write_text(_FAKE_MIGRATION)
    return migration_path


def _redirect_ads_path(monkeypatch, tmp_path: pathlib.Path):
    """Point the command's ``apps.get_app_config("ads")`` at the temp dir."""
    real = django_apps.get_app_config

    def fake(name: str):
        if name == "ads":
            return SimpleNamespace(path=str(tmp_path))
        return real(name)

    monkeypatch.setattr(cmd_module.apps, "get_app_config", fake)


class TestSquashRehydrateRunsql:
    """Tests for the squash_rehydrate_runsql command."""

    def test_dry_run_does_not_write(self, tmp_path, monkeypatch):
        migration_path = _write_fake_migration(tmp_path)
        _redirect_ads_path(monkeypatch, tmp_path)

        out = StringIO()
        call_command("squash_rehydrate_runsql", "--dry-run", stdout=out)

        stdout = out.getvalue()
        assert "Dry run" in stdout
        assert "migrations.RunSQL" in stdout
        # File must be untouched (still marker-free).
        assert MARKER not in migration_path.read_text()

    def test_injects_runsql_before_closing_bracket(self, tmp_path, monkeypatch):
        migration_path = _write_fake_migration(tmp_path)
        _redirect_ads_path(monkeypatch, tmp_path)

        out = StringIO()
        call_command("squash_rehydrate_runsql", stdout=out)

        stdout = out.getvalue()
        assert "Injected" in stdout

        source = migration_path.read_text()
        assert MARKER in source
        # 4 RunSQL ops, each referencing migrations.RunSQL twice (call + .noop).
        assert source.count("migrations.RunSQL") == 2 * len(DDL_STATEMENTS)
        # Every DDL statement's SQL is embedded verbatim (via repr()).
        for _label, sql in DDL_STATEMENTS:
            assert repr(sql) in source
        # The injected block lands inside the operations list (before the "]").
        assert source.rstrip().endswith("    ]")
        # The spliced migration must still be valid Python.
        ast.parse(source)

    def test_idempotent_on_rerun(self, tmp_path, monkeypatch):
        migration_path = _write_fake_migration(tmp_path)
        _redirect_ads_path(monkeypatch, tmp_path)

        call_command("squash_rehydrate_runsql")
        after_first = migration_path.read_text()

        out = StringIO()
        call_command("squash_rehydrate_runsql", stdout=out)
        assert "already present" in out.getvalue()

        # Second run must not change the file.
        assert migration_path.read_text() == after_first

    def test_missing_migration_reports_error(self, tmp_path, monkeypatch):
        # No migrations/ directory created -> file not found.
        _redirect_ads_path(monkeypatch, tmp_path)

        err = StringIO()
        call_command("squash_rehydrate_runsql", stderr=err)
        assert "Migration not found" in err.getvalue()
