# Generated by Django 5.2.16 on 2026-08-04 20:52

import apps.core.enums
import apps.lookups.enums
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order of this feature on the ad page')),
            ],
            options={
                'db_table': 'ad_features',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='Storage key (UUID v4 + .jpg, no ad_id/user/telegram PII)', max_length=64)),
                ('telegram_file_id', models.CharField(blank=True, help_text='Telegram file_id; NOT used in <img src>', max_length=255, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Image order in gallery')),
                ('thumbnail_small', models.CharField(blank=True, help_text='Storage key for small thumbnail (<uuid>-small.jpg)', max_length=64, null=True)),
                ('thumbnail_medium', models.CharField(blank=True, help_text='Storage key for medium thumbnail (<uuid>-medium.jpg)', max_length=64, null=True)),
                ('thumbnail_large', models.CharField(blank=True, help_text='Storage key for large thumbnail (<uuid>-large.jpg)', max_length=64, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex digest for deduplication', max_length=64)),
            ],
            options={
                'db_table': 'ad_images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ad title in Russian (translated from seller input)', max_length=200)),
                ('description', models.TextField(help_text='Ad description in Russian (translated from seller input)')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Whole BAM units; multi-currency deferred (YAGNI)', null=True)),
                ('category_name', models.CharField(editable=False, help_text='Denormalized Russian category name; trigger-synced', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('on_moderation', 'on_moderation'), ('published', 'published'), ('rejected', 'rejected'), ('on_moderation_failed', 'on_moderation_failed'), ('archived', 'archived'), ('deleted', 'deleted')], default=apps.core.enums.AdStatus['DRAFT'], help_text='Ad lifecycle status', max_length=20)),
                ('source', models.CharField(choices=[('telegram', 'telegram'), ('seed', 'seed')], default=apps.core.enums.AdSource['TELEGRAM'], help_text='Origin of ad (phase 1 = bot only)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Drives archive/delete timers; UPDATED on every PUBLISHED transition', null=True)),
                ('original_published_at', models.DateTimeField(blank=True, help_text='Set once on FIRST publish; IMMUTABLE, audit only', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='Auto-archive (2mo) or manual archive', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('moderation_failed_at', models.DateTimeField(blank=True, help_text='Failed auto-check; drives 7-day purge (mutually exclusive with rejected_at)', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='Manually rejected; drives 90-day cleanup (mutually exclusive with moderation_failed_at)', null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='TSVECTOR for native PostgreSQL FTS; NOT GENERATED ALWAYS', null=True)),
                ('category', models.ForeignKey(help_text='Ad category', on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='categories.category')),
                ('city', models.ForeignKey(help_text='Ad city location', on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='locations.city')),
                ('listing_purpose', models.ForeignKey(blank=True, help_text='What the user wants to do with the object', limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_PURPOSE']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='lookups.lookupitem')),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
