# Generated by Django 5.2.16 on 2026-08-28 21:38

import apps.core.enums
import apps.lookups.enums
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("locations", "0001_initial"),
        ("lookups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Ad title in Russian (translated from seller input)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Ad title in English",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "title_bs",
                    models.CharField(
                        blank=True,
                        help_text="Ad title in Bosnian",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Ad description in Russian (translated from seller input)",
                        null=True,
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, help_text="Ad description in English", null=True
                    ),
                ),
                (
                    "description_bs",
                    models.TextField(
                        blank=True, help_text="Ad description in Bosnian", null=True
                    ),
                ),
                (
                    "original_language",
                    models.CharField(
                        blank=True,
                        help_text="Original language code of the ad (e.g. 'ru', 'en', 'bs')",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Seller's original price amount (source of truth)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(
                        blank=True,
                        choices=[("EUR", "EUR"), ("RSD", "RSD"), ("BAM", "BAM")],
                        default="EUR",
                        help_text="Currency of the original price amount",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "price_normalized_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Derived price normalized to EUR for cross-currency filter/sort; not user-editable",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Denormalized Russian category name; trigger-synced. NULL during draft phase.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("on_moderation", "on_moderation"),
                            ("published", "published"),
                            ("rejected", "rejected"),
                            ("on_moderation_failed", "on_moderation_failed"),
                            ("archived", "archived"),
                            ("deleted", "deleted"),
                        ],
                        default=apps.core.enums.AdStatus["DRAFT"],
                        help_text="Ad lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("telegram", "telegram"), ("seed", "seed")],
                        default=apps.core.enums.AdSource["TELEGRAM"],
                        help_text="Origin of ad (phase 1 = bot only)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Drives archive/delete timers; UPDATED on every PUBLISHED transition",
                        null=True,
                    ),
                ),
                (
                    "original_published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set once on FIRST publish; IMMUTABLE, audit only",
                        null=True,
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-archive (2mo) or manual archive",
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
                (
                    "moderation_failed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Failed auto-check; drives 7-day purge (mutually exclusive with rejected_at)",
                        null=True,
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Manually rejected; drives 90-day cleanup (mutually exclusive with moderation_failed_at)",
                        null=True,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True,
                        help_text="TSVECTOR for native PostgreSQL FTS; NOT GENERATED ALWAYS",
                        null=True,
                    ),
                ),
                (
                    "search_vector_ru",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True,
                        help_text="Russian TSVECTOR for native PostgreSQL FTS; NOT GENERATED ALWAYS",
                        null=True,
                    ),
                ),
                (
                    "search_vector_bs",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True,
                        help_text="Bosnian TSVECTOR for native PostgreSQL FTS; NOT GENERATED ALWAYS",
                        null=True,
                    ),
                ),
                (
                    "search_vector_en",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True,
                        help_text="English TSVECTOR for native PostgreSQL FTS; NOT GENERATED ALWAYS",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ad category. NULL during draft phase.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ads",
                        to="categories.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ad city location. NULL during draft phase.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ads",
                        to="locations.city",
                    ),
                ),
                (
                    "listing_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item condition (new/used). NULL for categories without condition.",
                        limit_choices_to={
                            "group__code": apps.lookups.enums.LookupGroupCode[
                                "LISTING_CONDITION"
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_ads",
                        to="lookups.lookupitem",
                    ),
                ),
                (
                    "listing_purpose",
                    models.ForeignKey(
                        blank=True,
                        help_text="What the user wants to do with the object",
                        limit_choices_to={
                            "group__code": apps.lookups.enums.LookupGroupCode[
                                "LISTING_PURPOSE"
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ads",
                        to="lookups.lookupitem",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who manually rejected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who manually published",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Ad owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ads",
            },
        ),
        migrations.CreateModel(
            name="AdFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of this feature on the ad page",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_features",
                        to="ads.ad",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        limit_choices_to={
                            "group__code": apps.lookups.enums.LookupGroupCode[
                                "LISTING_FEATURE"
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lookups.lookupitem",
                    ),
                ),
            ],
            options={
                "db_table": "ad_features",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_ads",
                through="ads.AdFeature",
                through_fields=("ad", "feature"),
                to="lookups.lookupitem",
            ),
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        help_text="Storage key (UUID v4 + .jpg, no ad_id/user/telegram PII)",
                        max_length=64,
                    ),
                ),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True,
                        help_text="Telegram file_id; NOT used in <img src>",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Image order in gallery"
                    ),
                ),
                (
                    "thumbnail_small",
                    models.CharField(
                        blank=True,
                        help_text="Storage key for small thumbnail (<uuid>-small.jpg)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "thumbnail_medium",
                    models.CharField(
                        blank=True,
                        help_text="Storage key for medium thumbnail (<uuid>-medium.jpg)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "thumbnail_large",
                    models.CharField(
                        blank=True,
                        help_text="Storage key for large thumbnail (<uuid>-large.jpg)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 hex digest for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Parent ad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ads.ad",
                    ),
                ),
            ],
            options={
                "db_table": "ad_images",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="AdFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the ad was favorited"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="The favorited ad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="ads.ad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who favorited the ad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ad_favorites",
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="ad_favorites_user_created_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "ad"), name="uq_user_ad_favorite"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="adfeature",
            index=models.Index(fields=["feature"], name="IX_ad_features_feature_id"),
        ),
        migrations.AlterUniqueTogether(
            name="adfeature",
            unique_together={("ad", "feature")},
        ),
        migrations.AddIndex(
            model_name="ad",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="IX_ads_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_ru"], name="IX_ads_search_gin_ru"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_bs"], name="IX_ads_search_gin_bs"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_en"], name="IX_ads_search_gin_en"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("status", apps.core.enums.AdStatus["PUBLISHED"])),
                fields=["status", "category_id", "city_id", "-published_at"],
                name="IX_ads_pub_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("status", apps.core.enums.AdStatus["PUBLISHED"])),
                fields=["listing_purpose_id"],
                name="IX_ads_pub_purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(fields=["user_id", "status"], name="IX_ads_user_status"),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("price_normalized_eur__isnull", False)),
                fields=["price_normalized_eur"],
                name="IX_ads_price_normalized_eur",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("status", apps.core.enums.AdStatus["PUBLISHED"])),
                fields=["status", "published_at"],
                name="IX_ads_archive_sweep",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("status", apps.core.enums.AdStatus["ARCHIVED"])),
                fields=["status", "published_at"],
                name="IX_ads_delete_sweep",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(
                    ("status", apps.core.enums.AdStatus["ON_MODERATION_FAILED"])
                ),
                fields=["status", "moderation_failed_at"],
                name="IX_ads_purge_failed",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("status", apps.core.enums.AdStatus["REJECTED"])),
                fields=["status", "rejected_at"],
                name="IX_ads_rejected_sweep",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("status", apps.core.enums.AdStatus["DELETED"])),
                fields=["status", "deleted_at"],
                name="IX_ads_purge_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", apps.core.enums.AdStatus["PUBLISHED"]), _negated=True
                    ),
                    ("published_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_ads_published_at_if_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", apps.core.enums.AdStatus["ARCHIVED"]), _negated=True
                    ),
                    ("archived_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_ads_archived_at_if_archived",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", apps.core.enums.AdStatus["REJECTED"]), _negated=True
                    ),
                    ("rejected_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_ads_rejected_at_if_rejected",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", apps.core.enums.AdStatus["ON_MODERATION_FAILED"]),
                        _negated=True,
                    ),
                    ("moderation_failed_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_ads_moderation_failed_at_if_failed",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", apps.core.enums.AdStatus["DELETED"]), _negated=True
                    ),
                    ("deleted_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_ads_deleted_at_if_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("moderation_failed_at__isnull", True),
                    ("rejected_at__isnull", True),
                    _connector="OR",
                ),
                name="ck_ads_failed_and_rejected_mutually_exclusive",
            ),
        ),
        # SQUASH_REHYDRATE: trigger DDL
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE FUNCTION ads_search_vector_fn() RETURNS TRIGGER AS $$\nDECLARE\n  v_cat TEXT;\n  v_name_bs TEXT;\n  v_name_en TEXT;\nBEGIN\n  SELECT name, name_i18n->>'bs', name_i18n->>'en'\n    INTO v_cat, v_name_bs, v_name_en\n    FROM categories WHERE id = NEW.category_id;\n  NEW.category_name := v_cat;\n  NEW.search_vector :=\n    setweight(to_tsvector('russian', coalesce(NEW.title,'')), 'A') ||\n    setweight(to_tsvector('russian', coalesce(NEW.description,'')), 'B') ||\n    setweight(to_tsvector('simple', coalesce(NEW.title_bs,'')), 'A') ||\n    setweight(to_tsvector('simple', coalesce(NEW.description_bs,'')), 'B') ||\n    setweight(to_tsvector('english', coalesce(NEW.title_en,'')), 'A') ||\n    setweight(to_tsvector('english', coalesce(NEW.description_en,'')), 'B') ||\n    setweight(to_tsvector('simple', coalesce(v_cat,'')), 'C');\n  NEW.search_vector_ru :=\n    setweight(to_tsvector('russian', coalesce(NEW.title,'')), 'A') ||\n    setweight(to_tsvector('russian', coalesce(NEW.description,'')), 'B') ||\n    setweight(to_tsvector('russian', coalesce(v_cat,'')), 'C');\n  NEW.search_vector_bs :=\n    setweight(to_tsvector('simple', coalesce(NEW.title_bs,'')), 'A') ||\n    setweight(to_tsvector('simple', coalesce(NEW.description_bs,'')), 'B') ||\n    setweight(to_tsvector('simple', coalesce(coalesce(v_name_bs, v_cat),'')), 'C');\n  NEW.search_vector_en :=\n    setweight(to_tsvector('english', coalesce(NEW.title_en,'')), 'A') ||\n    setweight(to_tsvector('english', coalesce(NEW.description_en,'')), 'B') ||\n    setweight(to_tsvector('english', coalesce(coalesce(v_name_en, v_cat),'')), 'C');\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;\n",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE FUNCTION categories_name_propagate() RETURNS TRIGGER AS $$\nBEGIN\n  UPDATE ads SET category_name = NEW.name\n  WHERE category_id = NEW.id;\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;\n",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="\nDROP TRIGGER IF EXISTS ads_search_vector_update ON ads;\nCREATE TRIGGER ads_search_vector_update\n  BEFORE INSERT OR UPDATE ON ads\n  FOR EACH ROW EXECUTE FUNCTION ads_search_vector_fn();\n",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="\nDROP TRIGGER IF EXISTS on_category_name_update ON categories;\nCREATE TRIGGER on_category_name_update\n  AFTER UPDATE OF name, name_i18n ON categories\n  FOR EACH ROW EXECUTE FUNCTION categories_name_propagate();\n",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
