# Generated by Django 5.2.16 on 2026-09-10 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adimage",
            name="image",
            field=models.CharField(
                help_text="Storage key (UUID v4 + .jpg, no ad_id/user/telegram PII)",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Storage key must end in .jpg with no path traversal",
                        regex="^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="adimage",
            name="thumbnail_large",
            field=models.CharField(
                blank=True,
                help_text="Storage key for large thumbnail (<uuid>-large.jpg)",
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Storage key must end in .jpg with no path traversal",
                        regex="^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="adimage",
            name="thumbnail_medium",
            field=models.CharField(
                blank=True,
                help_text="Storage key for medium thumbnail (<uuid>-medium.jpg)",
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Storage key must end in .jpg with no path traversal",
                        regex="^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="adimage",
            name="thumbnail_small",
            field=models.CharField(
                blank=True,
                help_text="Storage key for small thumbnail (<uuid>-small.jpg)",
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Storage key must end in .jpg with no path traversal",
                        regex="^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="adimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "image__regex",
                        "^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    )
                ),
                name="ck_ad_images_image_key_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="adimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("thumbnail_small__isnull", True),
                    (
                        "thumbnail_small__regex",
                        "^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    ),
                    _connector="OR",
                ),
                name="ck_ad_images_thumb_small_key_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="adimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("thumbnail_medium__isnull", True),
                    (
                        "thumbnail_medium__regex",
                        "^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    ),
                    _connector="OR",
                ),
                name="ck_ad_images_thumb_medium_key_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="adimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("thumbnail_large__isnull", True),
                    (
                        "thumbnail_large__regex",
                        "^[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*\\.jpg$",
                    ),
                    _connector="OR",
                ),
                name="ck_ad_images_thumb_large_key_format",
            ),
        ),
    ]
