# Generated by Django 5.2.16 on 2026-08-03 21:32

import apps.core.enums
import apps.lookups.enums
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who manually rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who manually published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(help_text='Ad owner', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adfeature',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_features', to='ads.ad'),
        ),
        migrations.AddField(
            model_name='adfeature',
            name='feature',
            field=models.ForeignKey(limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_FEATURE']}, on_delete=django.db.models.deletion.CASCADE, to='lookups.lookupitem'),
        ),
        migrations.AddField(
            model_name='ad',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='featured_ads', through='ads.AdFeature', through_fields=('ad', 'feature'), to='lookups.lookupitem'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(help_text='Parent ad', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad'),
        ),
        migrations.AlterUniqueTogether(
            name='adfeature',
            unique_together={('ad', 'feature')},
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='IX_ads_search_gin'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['PUBLISHED'])), fields=['status', 'category_id', 'city_id', '-published_at'], name='IX_ads_pub_listing'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user_id', 'status'], name='IX_ads_user_status'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['PUBLISHED'])), fields=['status', 'published_at'], name='IX_ads_archive_sweep'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['ARCHIVED'])), fields=['status', 'published_at'], name='IX_ads_delete_sweep'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['ON_MODERATION_FAILED'])), fields=['status', 'moderation_failed_at'], name='IX_ads_purge_failed'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['REJECTED'])), fields=['status', 'rejected_at'], name='IX_ads_rejected_sweep'),
        ),
    ]
