# Generated by Django 5.2.16 on 2026-08-04 20:52

import apps.core.enums
import apps.lookups.enums
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SEARCH_VECTOR_FN_SQL = """
CREATE OR REPLACE FUNCTION ads_search_vector_fn() RETURNS TRIGGER AS $$
DECLARE v_cat TEXT;
BEGIN
  SELECT name INTO v_cat FROM categories WHERE id = NEW.category_id;
  NEW.category_name := v_cat;
  NEW.search_vector :=
    setweight(to_tsvector('russian', coalesce(NEW.title,'')), 'A') ||
    setweight(to_tsvector('russian', coalesce(NEW.description,'')), 'B') ||
    setweight(to_tsvector('russian', coalesce(v_cat,'')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

SEARCH_VECTOR_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS ads_search_vector_update ON ads;
CREATE TRIGGER ads_search_vector_update
  BEFORE INSERT OR UPDATE ON ads
  FOR EACH ROW EXECUTE FUNCTION ads_search_vector_fn();
"""

CATEGORY_PROPAGATE_FN_SQL = """
CREATE OR REPLACE FUNCTION categories_name_propagate() RETURNS TRIGGER AS $$
BEGIN
  UPDATE ads SET category_id = ads.category_id
  WHERE category_id = NEW.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CATEGORY_PROPAGATE_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS on_category_name_update ON categories;
CREATE TRIGGER on_category_name_update
  AFTER UPDATE OF name ON categories
  FOR EACH ROW EXECUTE FUNCTION categories_name_propagate();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who manually rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who manually published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(help_text='Ad owner', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adfeature',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_features', to='ads.ad'),
        ),
        migrations.AddField(
            model_name='adfeature',
            name='feature',
            field=models.ForeignKey(limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_FEATURE']}, on_delete=django.db.models.deletion.CASCADE, to='lookups.lookupitem'),
        ),
        migrations.AddField(
            model_name='ad',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='featured_ads', through='ads.AdFeature', through_fields=('ad', 'feature'), to='lookups.lookupitem'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(help_text='Parent ad', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad'),
        ),
        migrations.AlterUniqueTogether(
            name='adfeature',
            unique_together={('ad', 'feature')},
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='IX_ads_search_gin'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['PUBLISHED'])), fields=['status', 'category_id', 'city_id', '-published_at'], name='IX_ads_pub_listing'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user_id', 'status'], name='IX_ads_user_status'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['PUBLISHED'])), fields=['status', 'published_at'], name='IX_ads_archive_sweep'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['ARCHIVED'])), fields=['status', 'published_at'], name='IX_ads_delete_sweep'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['ON_MODERATION_FAILED'])), fields=['status', 'moderation_failed_at'], name='IX_ads_purge_failed'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['REJECTED'])), fields=['status', 'rejected_at'], name='IX_ads_rejected_sweep'),
        ),
        migrations.RunSQL(
            SEARCH_VECTOR_FN_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            SEARCH_VECTOR_TRIGGER_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            CATEGORY_PROPAGATE_FN_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            CATEGORY_PROPAGATE_TRIGGER_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
