# Generated by Django 5.2.16 on 2026-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_fks_and_search_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description_bs',
            field=models.TextField(blank=True, help_text='Ad description in Bosnian', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_en',
            field=models.TextField(blank=True, help_text='Ad description in English', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='original_language',
            field=models.CharField(blank=True, help_text="Original language code of the ad (e.g. 'ru', 'en', 'bs')", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_bs',
            field=models.CharField(blank=True, help_text='Ad title in Bosnian', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_en',
            field=models.CharField(blank=True, help_text='Ad title in English', max_length=200, null=True),
        ),
    ]
