# Generated by Django 5.2.16 on 2026-09-14 07:10

import apps.core.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_dedup_per_user_drafts'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.UniqueConstraint(condition=models.Q(('status', apps.core.enums.AdStatus['DRAFT'])), fields=('user_id',), name='uq_ads_single_draft_per_user'),
        ),
    ]
