# Generated by Django 5.2.16 on 2026-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_ad_i18n_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Ad title in Russian. NULL during draft phase.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Ad description in Russian. NULL during draft phase.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Ad category. NULL during draft phase.",
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="ads",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="Ad city location. NULL during draft phase.",
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="ads",
                to="locations.city",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="category_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Denormalized category name; trigger-synced. NULL during draft phase.",
                max_length=200,
                null=True,
            ),
        ),
    ]
