# Generated by Django 5.2.16 on 2026-09-14 07:44

from django.conf import settings
from django.db import migrations, models

import apps.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_uq_ads_single_draft_per_user'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='IX_ads_delete_sweep',
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['ARCHIVED'])), fields=['status', 'archived_at'], name='IX_ads_delete_sweep'),
        ),
    ]
