# Generated by Django 5.2.16 on 2026-08-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_draft_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category_name',
            field=models.CharField(blank=True, editable=False, help_text='Denormalized Russian category name; trigger-synced. NULL during draft phase.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, help_text='Ad description in Russian (translated from seller input)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, help_text='Ad title in Russian (translated from seller input)', max_length=200, null=True),
        ),
    ]
