# Generated by Django 5.2.16 on 2026-09-14 08:07

import apps.core.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_ix_ads_delete_sweep_ad_ix_ads_delete_sweep'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['DRAFT'])), fields=['status', 'created_at'], name='IX_ads_draft_sweep'),
        ),
    ]
