# Generated by Django 5.2.16 on 2026-08-16 21:10

import apps.core.enums
from django.conf import settings
from django.db import migrations, models


SEARCH_VECTOR_FN_SQL = """
CREATE OR REPLACE FUNCTION ads_search_vector_fn() RETURNS TRIGGER AS $$
DECLARE v_cat TEXT;
BEGIN
  SELECT name INTO v_cat FROM categories WHERE id = NEW.category_id;
  NEW.category_name := v_cat;
  NEW.search_vector :=
    setweight(to_tsvector('russian', coalesce(NEW.title,'')), 'A') ||
    setweight(to_tsvector('russian', coalesce(NEW.description,'')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW.title_bs,'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.description_bs,'')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.title_en,'')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.description_en,'')), 'B') ||
    setweight(to_tsvector('simple', coalesce(v_cat,'')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CATEGORY_PROPAGATE_FN_SQL = """
CREATE OR REPLACE FUNCTION categories_name_propagate() RETURNS TRIGGER AS $$
BEGIN
  UPDATE ads SET category_name = NEW.name
  WHERE category_id = NEW.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_category_name_alter_ad_description_and_more'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['DELETED'])), fields=['status', 'deleted_at'], name='IX_ads_purge_deleted'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.core.enums.AdStatus['PUBLISHED']), _negated=True), ('published_at__isnull', False), _connector='OR'), name='ck_ads_published_at_if_published'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.core.enums.AdStatus['ARCHIVED']), _negated=True), ('archived_at__isnull', False), _connector='OR'), name='ck_ads_archived_at_if_archived'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.core.enums.AdStatus['REJECTED']), _negated=True), ('rejected_at__isnull', False), _connector='OR'), name='ck_ads_rejected_at_if_rejected'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.core.enums.AdStatus['ON_MODERATION_FAILED']), _negated=True), ('moderation_failed_at__isnull', False), _connector='OR'), name='ck_ads_moderation_failed_at_if_failed'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.core.enums.AdStatus['DELETED']), _negated=True), ('deleted_at__isnull', False), _connector='OR'), name='ck_ads_deleted_at_if_deleted'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(('moderation_failed_at__isnull', True), ('rejected_at__isnull', True), _connector='OR'), name='ck_ads_failed_and_rejected_mutually_exclusive'),
        ),
        migrations.RunSQL(
            sql=CATEGORY_PROPAGATE_FN_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=SEARCH_VECTOR_FN_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='UPDATE ads SET title = title;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
