# Generated by Django 5.2.16 on 2026-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_ix_ads_draft_sweep'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adimage',
            index=models.Index(fields=['image'], name='IX_adimages_image'),
        ),
        migrations.AddIndex(
            model_name='adimage',
            index=models.Index(fields=['thumbnail_small'], name='IX_adimages_thumb_small'),
        ),
        migrations.AddIndex(
            model_name='adimage',
            index=models.Index(fields=['thumbnail_medium'], name='IX_adimages_thumb_medium'),
        ),
        migrations.AddIndex(
            model_name='adimage',
            index=models.Index(fields=['thumbnail_large'], name='IX_adimages_thumb_large'),
        ),
    ]
