# Generated by Django 5.2.17 on 2026-09-30 08:33

from django.conf import settings
from django.db import migrations, models

import apps.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_adimage_ix_adimages_image_and_more'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='IX_ads_draft_sweep',
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['DRAFT'])), fields=['status', 'updated_at'], name='IX_ads_draft_sweep'),
        ),
    ]
