# Generated by Django 5.2.16 on 2026-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0008_remove_ad_ix_ads_draft_sweep_ad_ix_ads_draft_sweep"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="adimage",
            constraint=models.UniqueConstraint(
                fields=("ad", "position"),
                name="uq_ad_images_ad_position",
            ),
        ),
    ]
