# Generated by Django 5.2.16 on 2026-08-22

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def backfill_price_fields(apps, schema_editor):
    """Backfill legacy ``price`` (BAM, PO-03) into the currency fields.

    Assumes all legacy prices are BAM (the old bot only ever accepted BAM).
    Sets ``price_currency = BAM``, ``price_amount = old_price`` and computes
    ``price_normalized_eur = old_price * BAM_to_EUR_rate`` using the seeded
    BAM rate from the ``ExchangeRate`` table (falls back to the recorded
    constant 0.512 if no current BAM rate exists). NULL price stays NULL.
    """
    Ad = apps.get_model("ads", "Ad")
    ExchangeRate = apps.get_model("currencies", "ExchangeRate")

    try:
        bam_rate = ExchangeRate.objects.get(currency="BAM", is_current=True).rate_to_eur
    except ExchangeRate.DoesNotExist:
        bam_rate = "0.512"

    bam_rate = Decimal(str(bam_rate))

    batch_size = 1000
    for ad in Ad.objects.filter(price__isnull=False).iterator(chunk_size=batch_size):
        old_price = ad.price
        normalized = (Decimal(str(old_price)) * bam_rate).quantize(
            Decimal("0.0001"), rounding=ROUND_HALF_UP
        )
        Ad.objects.filter(pk=ad.pk).update(
            price_currency="BAM",
            price_amount=old_price,
            price_normalized_eur=normalized,
        )


def remove_backfill_price_fields(apps, schema_editor):
    """Reverse: restore the legacy ``price`` column from price_amount.

    Reverse data migration is best-effort: it restores ``price`` from
    ``price_amount`` for rows that were backfilled (BAM), dropping the
    normalized/currency columns via ``RemoveField`` on reverse below.
    """
    Ad = apps.get_model("ads", "Ad")
    for ad in Ad.objects.filter(price_amount__isnull=False).iterator(chunk_size=1000):
        Ad.objects.filter(pk=ad.pk).update(price=ad.price_amount)


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_adfavorite"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Seller's original price amount (source of truth)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="price_currency",
            field=models.CharField(
                blank=True,
                choices=[("EUR", "EUR"), ("RSD", "RSD"), ("BAM", "BAM")],
                default="EUR",
                help_text="Currency of the original price amount",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="price_normalized_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Derived price normalized to EUR for cross-currency filter/sort; not user-editable",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_price_fields, remove_backfill_price_fields),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(("price_normalized_eur__isnull", False)),
                fields=["price_normalized_eur"],
                name="IX_ads_price_normalized_eur",
            ),
        ),
        migrations.RemoveField(
            model_name="ad",
            name="price",
        ),
    ]
