# Generated by Django 5.2.16

from django.db import migrations, models

import apps.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_adimage_uq_ad_position'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(
                condition=models.Q(('status', apps.core.enums.AdStatus['PUBLISHED'])),
                fields=['price_normalized_eur'],
                name='IX_ads_pub_price_sort',
            ),
        ),
    ]
