# Generated by Django 5.2.16 on 2026-08-22 16:48

import apps.core.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ad_currency_price_fields'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('status', apps.core.enums.AdStatus['PUBLISHED'])), fields=['listing_purpose_id'], name='IX_ads_pub_purpose'),
        ),
        migrations.AddIndex(
            model_name='adfeature',
            index=models.Index(fields=['feature'], name='IX_ad_features_feature_id'),
        ),
    ]
