# Generated by Django 5.2.16 on 2026-08-25 20:16

import apps.lookups.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_catalog_filter_indexes'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='listing_condition',
            field=models.ForeignKey(blank=True, help_text='Item condition (new/used). NULL for categories without condition.', limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_CONDITION']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condition_ads', to='lookups.lookupitem'),
        ),
    ]
