# Generated by Django 5.2.16 on 2026-08-28 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('query_normalized', models.CharField(db_index=True, max_length=200)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, choices=[('telegram', 'telegram'), ('seed', 'seed')], db_index=True, default=None, help_text="Origin of record (null = production, 'seed' = seed-generated)", max_length=20, null=True)),
            ],
            options={
                'db_table': 'popular_searches',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, help_text='FTS query string (translated to Russian if Bosnian input)', null=True)),
                ('min_price', models.PositiveIntegerField(blank=True, help_text='Minimum price filter, EUR-equivalent value (WR-04)', null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, help_text='Maximum price filter, EUR-equivalent value (WR-04)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive searches do not receive notifications')),
                ('language', models.CharField(blank=True, default='bs', help_text="LanguageLocale code ('ru', 'bs' or 'en') used to search ads", max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this saved search was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this saved search was last modified')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time this search produced a notification', null=True)),
                ('unsubscribe_token', models.CharField(blank=True, db_index=True, help_text='Opaque server-generated capability token for Telegram unsubscribe deep-links and inline callbacks (never derived from the PK)', max_length=40, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category filter (includes descendants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='categories.category')),
                ('city', models.ForeignKey(blank=True, help_text='Optional city filter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='locations.city')),
                ('user', models.ForeignKey(help_text='User who saved this search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_searches',
            },
        ),
        migrations.CreateModel(
            name='SavedSearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was sent')),
                ('ad', models.ForeignKey(help_text='The ad that was sent in the notification', on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_notifications', to='ads.ad')),
                ('saved_search', models.ForeignKey(help_text='The saved search this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='search.savedsearch')),
            ],
            options={
                'db_table': 'saved_search_notifications',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('query_normalized', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user_id', 'is_active'], name='IX_saved_searches_user_active'),
        ),
        migrations.AddIndex(
            model_name='savedsearchnotification',
            index=models.Index(fields=['saved_search_id'], name='idx_saved_search_notif_sid'),
        ),
        migrations.AddConstraint(
            model_name='savedsearchnotification',
            constraint=models.UniqueConstraint(fields=('saved_search', 'ad'), name='uq_saved_search_ad'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user_id', '-created_at'], name='search_hist_user_id_3ea0ad_idx'),
        ),
    ]
