# Generated by Django 5.2.16 on 2026-08-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('query_normalized', models.CharField(db_index=True, max_length=200)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'popular_searches',
            },
        ),
        migrations.CreateModel(
            name='SavedSearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was sent')),
            ],
            options={
                'db_table': 'saved_search_notifications',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('query_normalized', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, help_text='FTS query string (translated to Russian if Bosnian input)', null=True)),
                ('min_price', models.PositiveIntegerField(blank=True, help_text='Minimum price filter in BAM', null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, help_text='Maximum price filter in BAM', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive searches do not receive notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this saved search was created')),
                ('category', models.ForeignKey(blank=True, help_text='Optional category filter (includes descendants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='categories.category')),
                ('city', models.ForeignKey(blank=True, help_text='Optional city filter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='locations.city')),
            ],
            options={
                'db_table': 'saved_searches',
            },
        ),
    ]
