# Generated by Django 5.2.16 on 2026-08-04 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_fks_and_search_triggers'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(help_text='User who saved this search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedsearchnotification',
            name='ad',
            field=models.ForeignKey(help_text='The ad that was sent in the notification', on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_notifications', to='ads.ad'),
        ),
        migrations.AddField(
            model_name='savedsearchnotification',
            name='saved_search',
            field=models.ForeignKey(help_text='The saved search this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='search.savedsearch'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user_id', 'is_active'], name='IX_saved_searches_user_active'),
        ),
        migrations.AddIndex(
            model_name='savedsearchnotification',
            index=models.Index(fields=['saved_search_id'], name='idx_saved_search_notif_sid'),
        ),
        migrations.AddConstraint(
            model_name='savedsearchnotification',
            constraint=models.UniqueConstraint(fields=('saved_search', 'ad'), name='uq_saved_search_ad'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user_id', '-created_at'], name='search_hist_user_id_3ea0ad_idx'),
        ),
    ]
