# Generated by Django 5.2.17 on 2026-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_redact_search_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearchnotification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text="Receipt: when Telegram accepted the alert for this pair. Written AFTER a successful send by both delivery paths. NULL means 'recorded but not delivered', so the pair stays eligible for the immediate and daily paths. One alert per (saved_search, ad) for the life of the listing, including across a re-publish, is a recorded product decision.", null=True),
        ),
        migrations.AlterField(
            model_name='savedsearchnotification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the notification record was created'),
        ),
    ]
