# Generated by Django 5.2.16 on 2026-08-22
# Data migration: convert existing saved-search min/max prices from BAM to EUR.

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations

# Seeded BAM->EUR rate (PO-04/PO-05). Must match the seed constant so the
# conversion stays consistent with ad price normalization.
BAM_TO_EUR = Decimal("0.512")


def convert_saved_search_prices(apps, schema_editor):
    """Convert existing SavedSearch min_price/max_price from BAM to EUR.

    Existing saved searches stored min/max in BAM (the old hardcoded unit).
    After reinterpreting these filters as EUR-equivalent (WR-04/PO-04) their
    values must be multiplied by the BAM->EUR seed rate. NULL values stay NULL.
    """
    SavedSearch = apps.get_model("search", "SavedSearch")
    for search in SavedSearch.objects.all():
        update_fields = {}
        if search.min_price is not None:
            update_fields["min_price"] = int(
                (Decimal(str(search.min_price)) * BAM_TO_EUR).quantize(
                    Decimal("1"), rounding=ROUND_HALF_UP
                )
            )
        if search.max_price is not None:
            update_fields["max_price"] = int(
                (Decimal(str(search.max_price)) * BAM_TO_EUR).quantize(
                    Decimal("1"), rounding=ROUND_HALF_UP
                )
            )
        if update_fields:
            SavedSearch.objects.filter(pk=search.pk).update(**update_fields)


def reverse_convert_saved_search_prices(apps, schema_editor):
    """Reverse: convert saved-search prices back from EUR to BAM."""
    SavedSearch = apps.get_model("search", "SavedSearch")
    for search in SavedSearch.objects.all():
        update_fields = {}
        if search.min_price is not None:
            update_fields["min_price"] = int(
                (Decimal(str(search.min_price)) / BAM_TO_EUR).quantize(
                    Decimal("1"), rounding=ROUND_HALF_UP
                )
            )
        if search.max_price is not None:
            update_fields["max_price"] = int(
                (Decimal(str(search.max_price)) / BAM_TO_EUR).quantize(
                    Decimal("1"), rounding=ROUND_HALF_UP
                )
            )
        if update_fields:
            SavedSearch.objects.filter(pk=search.pk).update(**update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_savedsearch_alerts_fields"),
    ]

    operations = [
        migrations.RunPython(
            convert_saved_search_prices,
            reverse_convert_saved_search_prices,
        ),
    ]
