# Generated by Django 5.2.16 on 2026-08-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_savedsearch_price_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum price filter, EUR-equivalent value (WR-04)', null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum price filter, EUR-equivalent value (WR-04)', null=True),
        ),
    ]
