# Generated by Django 5.2.16 on 2026-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_savedsearch_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularsearch',
            name='source',
            field=models.CharField(blank=True, choices=[('telegram', 'telegram'), ('seed', 'seed')], db_index=True, default=None, help_text="Origin of record (null = production, 'seed' = seed-generated)", max_length=20, null=True),
        ),
    ]
