# Generated by Django 5.2.16 on 2026-08-04 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered event (SET NULL on erasure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyadmetrics',
            name='ad',
            field=models.ForeignKey(help_text='Ad this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='ads.ad'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='idx_analytics_evt_ts'),
        ),
        migrations.AddIndex(
            model_name='dailyadmetrics',
            index=models.Index(fields=['date', '-views_count'], name='idx_daily_metrics_date_views'),
        ),
        migrations.AddConstraint(
            model_name='dailyadmetrics',
            constraint=models.UniqueConstraint(fields=('ad', 'date'), name='uq_daily_ad_metrics_ad_date'),
        ),
    ]
