# Generated by Django 5.2.16 on 2026-08-10 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Event timestamp'),
        ),
    ]
