# Generated by Django 5.2.16 on 2026-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_change_timestamp_auto_add_to_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='source',
            field=models.CharField(blank=True, choices=[('telegram', 'telegram'), ('seed', 'seed')], db_index=True, default=None, help_text="Origin of event (null = production, 'seed' = seed-generated)", max_length=20, null=True),
        ),
    ]
