--
-- PostgreSQL database dump
--

\restrict Ql6CX068oN0YEYgGDta5HBg3PgZnrCcqUte7vnef7xz0sQ174ESYiYzEj1LrUs1

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ads_search_vector_fn(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.ads_search_vector_fn() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_cat TEXT;
  v_name_bs TEXT;
  v_name_en TEXT;
BEGIN
  SELECT name, name_i18n->>'bs', name_i18n->>'en'
    INTO v_cat, v_name_bs, v_name_en
    FROM categories WHERE id = NEW.category_id;
  NEW.category_name := v_cat;
  NEW.search_vector :=
    setweight(to_tsvector('russian', coalesce(NEW.title,'')), 'A') ||
    setweight(to_tsvector('russian', coalesce(NEW.description,'')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW.title_bs,'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.description_bs,'')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.title_en,'')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.description_en,'')), 'B') ||
    setweight(to_tsvector('simple', coalesce(v_cat,'')), 'C');
  NEW.search_vector_ru :=
    setweight(to_tsvector('russian', coalesce(NEW.title,'')), 'A') ||
    setweight(to_tsvector('russian', coalesce(NEW.description,'')), 'B') ||
    setweight(to_tsvector('russian', coalesce(v_cat,'')), 'C');
  NEW.search_vector_bs :=
    setweight(to_tsvector('simple', coalesce(NEW.title_bs,'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.description_bs,'')), 'B') ||
    setweight(to_tsvector('simple', coalesce(coalesce(v_name_bs, v_cat),'')), 'C');
  NEW.search_vector_en :=
    setweight(to_tsvector('english', coalesce(NEW.title_en,'')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.description_en,'')), 'B') ||
    setweight(to_tsvector('english', coalesce(coalesce(v_name_en, v_cat),'')), 'C');
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.ads_search_vector_fn() OWNER TO postgres;

--
-- Name: categories_name_propagate(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.categories_name_propagate() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  UPDATE ads SET category_name = NEW.name
  WHERE category_id = NEW.id;
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.categories_name_propagate() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ad_favorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ad_favorites (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    ad_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.ad_favorites OWNER TO postgres;

--
-- Name: ad_favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ad_favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ad_favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ad_features; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ad_features (
    id bigint NOT NULL,
    sort_order integer NOT NULL,
    ad_id bigint NOT NULL,
    feature_id bigint NOT NULL,
    CONSTRAINT ad_features_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.ad_features OWNER TO postgres;

--
-- Name: ad_features_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ad_features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ad_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ad_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ad_images (
    id bigint NOT NULL,
    image character varying(64) NOT NULL,
    telegram_file_id character varying(255),
    "position" integer NOT NULL,
    thumbnail_small character varying(64),
    thumbnail_medium character varying(64),
    thumbnail_large character varying(64),
    sha256 character varying(64) NOT NULL,
    ad_id bigint NOT NULL,
    CONSTRAINT ad_images_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.ad_images OWNER TO postgres;

--
-- Name: ad_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ad_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ad_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ad_moderation_priorities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ad_moderation_priorities (
    id bigint NOT NULL,
    base_score smallint NOT NULL,
    priority_level character varying(10) NOT NULL,
    flags jsonb NOT NULL,
    confidence_score double precision NOT NULL,
    escalation_required boolean NOT NULL,
    ad_id bigint NOT NULL,
    CONSTRAINT ad_moderation_priorities_base_score_check CHECK ((base_score >= 0))
);


ALTER TABLE public.ad_moderation_priorities OWNER TO postgres;

--
-- Name: ad_moderation_priorities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ad_moderation_priorities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ad_moderation_priorities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ads (
    id bigint NOT NULL,
    title character varying(200),
    description text,
    category_name character varying(200),
    status character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    published_at timestamp with time zone,
    original_published_at timestamp with time zone,
    archived_at timestamp with time zone,
    deleted_at timestamp with time zone,
    moderation_failed_at timestamp with time zone,
    rejected_at timestamp with time zone,
    search_vector tsvector,
    category_id bigint,
    city_id bigint,
    listing_purpose_id bigint,
    moderated_by_id bigint,
    published_by_id bigint,
    user_id bigint NOT NULL,
    description_bs text,
    description_en text,
    original_language character varying(5),
    title_bs character varying(200),
    title_en character varying(200),
    search_vector_ru tsvector,
    search_vector_bs tsvector,
    search_vector_en tsvector,
    price_amount numeric(10,2),
    price_currency character varying(3),
    price_normalized_eur numeric(12,4),
    listing_condition_id bigint,
    CONSTRAINT ck_ads_archived_at_if_archived CHECK (((NOT ((status)::text = 'archived'::text)) OR (archived_at IS NOT NULL))),
    CONSTRAINT ck_ads_deleted_at_if_deleted CHECK (((NOT ((status)::text = 'deleted'::text)) OR (deleted_at IS NOT NULL))),
    CONSTRAINT ck_ads_failed_and_rejected_mutually_exclusive CHECK (((moderation_failed_at IS NULL) OR (rejected_at IS NULL))),
    CONSTRAINT ck_ads_moderation_failed_at_if_failed CHECK (((NOT ((status)::text = 'on_moderation_failed'::text)) OR (moderation_failed_at IS NOT NULL))),
    CONSTRAINT ck_ads_published_at_if_published CHECK (((NOT ((status)::text = 'published'::text)) OR (published_at IS NOT NULL))),
    CONSTRAINT ck_ads_rejected_at_if_rejected CHECK (((NOT ((status)::text = 'rejected'::text)) OR (rejected_at IS NOT NULL)))
);


ALTER TABLE public.ads OWNER TO postgres;

--
-- Name: ads_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_events (
    id bigint NOT NULL,
    event_type character varying(30) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    ad_id bigint,
    user_id bigint,
    source character varying(20)
);


ALTER TABLE public.analytics_events OWNER TO postgres;

--
-- Name: analytics_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    name_i18n jsonb,
    slug character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    lft integer NOT NULL,
    rght integer NOT NULL,
    tree_id integer NOT NULL,
    level integer NOT NULL,
    parent_id bigint,
    CONSTRAINT categories_level_check CHECK ((level >= 0)),
    CONSTRAINT categories_lft_check CHECK ((lft >= 0)),
    CONSTRAINT categories_rght_check CHECK ((rght >= 0)),
    CONSTRAINT categories_tree_id_check CHECK ((tree_id >= 0))
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_listing_conditions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_listing_conditions (
    id bigint NOT NULL,
    category_id bigint NOT NULL,
    listing_condition_id bigint NOT NULL
);


ALTER TABLE public.category_listing_conditions OWNER TO postgres;

--
-- Name: category_listing_conditions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category_listing_conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_listing_conditions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_listing_features; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_listing_features (
    id bigint NOT NULL,
    category_id bigint NOT NULL,
    feature_id bigint NOT NULL
);


ALTER TABLE public.category_listing_features OWNER TO postgres;

--
-- Name: category_listing_features_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category_listing_features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_listing_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_listing_purposes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_listing_purposes (
    id bigint NOT NULL,
    is_default boolean NOT NULL,
    category_id bigint NOT NULL,
    listing_purpose_id bigint NOT NULL
);


ALTER TABLE public.category_listing_purposes OWNER TO postgres;

--
-- Name: category_listing_purposes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category_listing_purposes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_listing_purposes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_paths; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_paths (
    id bigint NOT NULL,
    sort_order integer NOT NULL,
    is_automatic boolean NOT NULL,
    category_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    CONSTRAINT category_paths_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.category_paths OWNER TO postgres;

--
-- Name: category_paths_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category_paths ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_paths_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    id bigint NOT NULL,
    country_code character varying(2) NOT NULL,
    name character varying(200) NOT NULL,
    name_i18n jsonb,
    region character varying(100) NOT NULL,
    slug character varying(50) NOT NULL
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consent_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consent_records (
    id bigint NOT NULL,
    session_key character varying(40),
    consent_given_at timestamp with time zone NOT NULL,
    consent_version character varying(20) NOT NULL,
    choice character varying(20) NOT NULL,
    categories jsonb NOT NULL,
    ip_address inet,
    user_agent text NOT NULL,
    user_id bigint
);


ALTER TABLE public.consent_records OWNER TO postgres;

--
-- Name: consent_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consent_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consent_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_ad_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.daily_ad_metrics (
    id bigint NOT NULL,
    date date NOT NULL,
    views_count integer NOT NULL,
    contacts_count integer NOT NULL,
    trust_score double precision,
    avg_response_time double precision,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    ad_id bigint NOT NULL,
    CONSTRAINT daily_ad_metrics_contacts_count_check CHECK ((contacts_count >= 0)),
    CONSTRAINT daily_ad_metrics_views_count_check CHECK ((views_count >= 0))
);


ALTER TABLE public.daily_ad_metrics OWNER TO postgres;

--
-- Name: daily_ad_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.daily_ad_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_ad_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: exchange_rates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exchange_rates (
    id bigint NOT NULL,
    currency character varying(3) NOT NULL,
    rate_to_eur numeric(14,8) NOT NULL,
    effective_date date NOT NULL,
    source character varying(50) NOT NULL,
    is_current boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.exchange_rates OWNER TO postgres;

--
-- Name: exchange_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exchange_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.login_tokens (
    id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    telegram_id bigint,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);


ALTER TABLE public.login_tokens OWNER TO postgres;

--
-- Name: login_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.login_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lookup_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lookup_groups (
    id bigint NOT NULL,
    code character varying(100) NOT NULL,
    name_i18n jsonb,
    is_system boolean NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT lookup_groups_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.lookup_groups OWNER TO postgres;

--
-- Name: lookup_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lookup_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lookup_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lookup_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lookup_items (
    id bigint NOT NULL,
    slug character varying(100) NOT NULL,
    name_i18n jsonb,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    icon character varying(50) NOT NULL,
    color character varying(7) NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT lookup_items_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.lookup_items OWNER TO postgres;

--
-- Name: lookup_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lookup_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lookup_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moderation_action_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.moderation_action_logs (
    id bigint NOT NULL,
    action_type character varying(20) NOT NULL,
    reason text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    ad_id bigint,
    user_id bigint
);


ALTER TABLE public.moderation_action_logs OWNER TO postgres;

--
-- Name: moderation_action_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.moderation_action_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moderation_action_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moderation_criteria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.moderation_criteria (
    id bigint NOT NULL,
    title_min_length integer NOT NULL,
    title_max_length integer NOT NULL,
    description_min_length integer NOT NULL,
    description_max_length integer NOT NULL,
    price_required boolean NOT NULL,
    min_images integer NOT NULL,
    max_images integer NOT NULL,
    banned_words jsonb NOT NULL,
    max_ads_per_user integer NOT NULL,
    duplicate_title_threshold integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    updated_by_id bigint,
    CONSTRAINT moderation_criteria_description_max_length_check CHECK ((description_max_length >= 0)),
    CONSTRAINT moderation_criteria_description_min_length_check CHECK ((description_min_length >= 0)),
    CONSTRAINT moderation_criteria_duplicate_title_threshold_check CHECK ((duplicate_title_threshold >= 0)),
    CONSTRAINT moderation_criteria_max_ads_per_user_check CHECK ((max_ads_per_user >= 0)),
    CONSTRAINT moderation_criteria_max_images_check CHECK ((max_images >= 0)),
    CONSTRAINT moderation_criteria_min_images_check CHECK ((min_images >= 0)),
    CONSTRAINT moderation_criteria_title_max_length_check CHECK ((title_max_length >= 0)),
    CONSTRAINT moderation_criteria_title_min_length_check CHECK ((title_min_length >= 0))
);


ALTER TABLE public.moderation_criteria OWNER TO postgres;

--
-- Name: moderation_criteria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.moderation_criteria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moderation_criteria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: popular_searches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.popular_searches (
    id bigint NOT NULL,
    query character varying(200) NOT NULL,
    query_normalized character varying(200) NOT NULL,
    hit_count integer NOT NULL,
    last_seen timestamp with time zone NOT NULL,
    source character varying(20),
    CONSTRAINT popular_searches_hit_count_check CHECK ((hit_count >= 0))
);


ALTER TABLE public.popular_searches OWNER TO postgres;

--
-- Name: popular_searches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.popular_searches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.popular_searches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_search_notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_search_notifications (
    id bigint NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    ad_id bigint NOT NULL,
    saved_search_id bigint NOT NULL
);


ALTER TABLE public.saved_search_notifications OWNER TO postgres;

--
-- Name: saved_search_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.saved_search_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_search_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_searches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_searches (
    id bigint NOT NULL,
    query text,
    min_price integer,
    max_price integer,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint,
    city_id bigint,
    user_id bigint NOT NULL,
    language character varying(5),
    updated_at timestamp with time zone NOT NULL,
    last_notified_at timestamp with time zone,
    unsubscribe_token character varying(40),
    CONSTRAINT saved_searches_max_price_check CHECK ((max_price >= 0)),
    CONSTRAINT saved_searches_min_price_check CHECK ((min_price >= 0))
);


ALTER TABLE public.saved_searches OWNER TO postgres;

--
-- Name: saved_searches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.saved_searches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_searches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.search_history (
    id bigint NOT NULL,
    query character varying(200) NOT NULL,
    query_normalized character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.search_history OWNER TO postgres;

--
-- Name: search_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.search_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_trust_scores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seller_trust_scores (
    id bigint NOT NULL,
    trust_level character varying(20) NOT NULL,
    score smallint NOT NULL,
    ad_count_lifetime integer NOT NULL,
    ad_count_active integer NOT NULL,
    rejection_rate numeric(5,2) NOT NULL,
    contact_response_rate numeric(5,2) NOT NULL,
    last_calculated timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT seller_trust_scores_ad_count_active_check CHECK ((ad_count_active >= 0)),
    CONSTRAINT seller_trust_scores_ad_count_lifetime_check CHECK ((ad_count_lifetime >= 0)),
    CONSTRAINT seller_trust_scores_score_check CHECK ((score >= 0))
);


ALTER TABLE public.seller_trust_scores OWNER TO postgres;

--
-- Name: seller_trust_scores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seller_trust_scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_trust_scores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seller_verifications (
    id bigint NOT NULL,
    phone_number character varying(20),
    verified_by_admin boolean NOT NULL,
    verified_at timestamp with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.seller_verifications OWNER TO postgres;

--
-- Name: seller_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seller_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(150),
    telegram_id bigint,
    chat_id bigint NOT NULL,
    is_banned boolean NOT NULL,
    is_deleted boolean NOT NULL,
    is_declined boolean NOT NULL,
    ads_auto_publish boolean NOT NULL,
    telegram_premium boolean NOT NULL,
    deleted_at timestamp with time zone,
    consent_given_at timestamp with time zone,
    consent_revoked_at timestamp with time zone,
    preferred_city_id bigint,
    telegram_language character varying(5) NOT NULL,
    source character varying(20)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ad_favorites ad_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_favorites
    ADD CONSTRAINT ad_favorites_pkey PRIMARY KEY (id);


--
-- Name: ad_features ad_features_ad_id_feature_id_3abf361f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_features
    ADD CONSTRAINT ad_features_ad_id_feature_id_3abf361f_uniq UNIQUE (ad_id, feature_id);


--
-- Name: ad_features ad_features_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_features
    ADD CONSTRAINT ad_features_pkey PRIMARY KEY (id);


--
-- Name: ad_images ad_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_images
    ADD CONSTRAINT ad_images_pkey PRIMARY KEY (id);


--
-- Name: ad_moderation_priorities ad_moderation_priorities_ad_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_moderation_priorities
    ADD CONSTRAINT ad_moderation_priorities_ad_id_key UNIQUE (ad_id);


--
-- Name: ad_moderation_priorities ad_moderation_priorities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_moderation_priorities
    ADD CONSTRAINT ad_moderation_priorities_pkey PRIMARY KEY (id);


--
-- Name: ads ads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_pkey PRIMARY KEY (id);


--
-- Name: analytics_events analytics_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT analytics_events_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: categories categories_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_slug_key UNIQUE (slug);


--
-- Name: category_listing_conditions category_listing_conditi_category_id_listing_cond_6b4bcfc6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_conditions
    ADD CONSTRAINT category_listing_conditi_category_id_listing_cond_6b4bcfc6_uniq UNIQUE (category_id, listing_condition_id);


--
-- Name: category_listing_conditions category_listing_conditions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_conditions
    ADD CONSTRAINT category_listing_conditions_pkey PRIMARY KEY (id);


--
-- Name: category_listing_features category_listing_features_category_id_feature_id_aac52939_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_features
    ADD CONSTRAINT category_listing_features_category_id_feature_id_aac52939_uniq UNIQUE (category_id, feature_id);


--
-- Name: category_listing_features category_listing_features_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_features
    ADD CONSTRAINT category_listing_features_pkey PRIMARY KEY (id);


--
-- Name: category_listing_purposes category_listing_purpose_category_id_listing_purp_6c6f16da_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_purposes
    ADD CONSTRAINT category_listing_purpose_category_id_listing_purp_6c6f16da_uniq UNIQUE (category_id, listing_purpose_id);


--
-- Name: category_listing_purposes category_listing_purposes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_purposes
    ADD CONSTRAINT category_listing_purposes_pkey PRIMARY KEY (id);


--
-- Name: category_paths category_paths_category_id_parent_id_4aeaa411_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_paths
    ADD CONSTRAINT category_paths_category_id_parent_id_4aeaa411_uniq UNIQUE (category_id, parent_id);


--
-- Name: category_paths category_paths_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_paths
    ADD CONSTRAINT category_paths_pkey PRIMARY KEY (id);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: cities cities_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_slug_key UNIQUE (slug);


--
-- Name: consent_records consent_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consent_records
    ADD CONSTRAINT consent_records_pkey PRIMARY KEY (id);


--
-- Name: daily_ad_metrics daily_ad_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_ad_metrics
    ADD CONSTRAINT daily_ad_metrics_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: exchange_rates exchange_rates_currency_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT exchange_rates_currency_key UNIQUE (currency);


--
-- Name: exchange_rates exchange_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (id);


--
-- Name: login_tokens login_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_tokens
    ADD CONSTRAINT login_tokens_pkey PRIMARY KEY (id);


--
-- Name: login_tokens login_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_tokens
    ADD CONSTRAINT login_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: lookup_groups lookup_groups_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lookup_groups
    ADD CONSTRAINT lookup_groups_code_key UNIQUE (code);


--
-- Name: lookup_groups lookup_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lookup_groups
    ADD CONSTRAINT lookup_groups_pkey PRIMARY KEY (id);


--
-- Name: lookup_items lookup_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lookup_items
    ADD CONSTRAINT lookup_items_pkey PRIMARY KEY (id);


--
-- Name: lookup_items lookup_items_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lookup_items
    ADD CONSTRAINT lookup_items_slug_key UNIQUE (slug);


--
-- Name: moderation_action_logs moderation_action_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderation_action_logs
    ADD CONSTRAINT moderation_action_logs_pkey PRIMARY KEY (id);


--
-- Name: moderation_criteria moderation_criteria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderation_criteria
    ADD CONSTRAINT moderation_criteria_pkey PRIMARY KEY (id);


--
-- Name: popular_searches popular_searches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.popular_searches
    ADD CONSTRAINT popular_searches_pkey PRIMARY KEY (id);


--
-- Name: saved_search_notifications saved_search_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_search_notifications
    ADD CONSTRAINT saved_search_notifications_pkey PRIMARY KEY (id);


--
-- Name: saved_searches saved_searches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_searches
    ADD CONSTRAINT saved_searches_pkey PRIMARY KEY (id);


--
-- Name: saved_searches saved_searches_unsubscribe_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_searches
    ADD CONSTRAINT saved_searches_unsubscribe_token_key UNIQUE (unsubscribe_token);


--
-- Name: search_history search_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_pkey PRIMARY KEY (id);


--
-- Name: seller_trust_scores seller_trust_scores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seller_trust_scores
    ADD CONSTRAINT seller_trust_scores_pkey PRIMARY KEY (id);


--
-- Name: seller_trust_scores seller_trust_scores_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seller_trust_scores
    ADD CONSTRAINT seller_trust_scores_user_id_key UNIQUE (user_id);


--
-- Name: seller_verifications seller_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seller_verifications
    ADD CONSTRAINT seller_verifications_pkey PRIMARY KEY (id);


--
-- Name: seller_verifications seller_verifications_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seller_verifications
    ADD CONSTRAINT seller_verifications_user_id_key UNIQUE (user_id);


--
-- Name: daily_ad_metrics uq_daily_ad_metrics_ad_date; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_ad_metrics
    ADD CONSTRAINT uq_daily_ad_metrics_ad_date UNIQUE (ad_id, date);


--
-- Name: saved_search_notifications uq_saved_search_ad; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_search_notifications
    ADD CONSTRAINT uq_saved_search_ad UNIQUE (saved_search_id, ad_id);


--
-- Name: ad_favorites uq_user_ad_favorite; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_favorites
    ADD CONSTRAINT uq_user_ad_favorite UNIQUE (user_id, ad_id);


--
-- Name: users users_chat_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_chat_id_key UNIQUE (chat_id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_telegram_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_telegram_id_key UNIQUE (telegram_id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: IX_ad_features_feature_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ad_features_feature_id" ON public.ad_features USING btree (feature_id);


--
-- Name: IX_ads_archive_sweep; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_archive_sweep" ON public.ads USING btree (status, published_at) WHERE ((status)::text = 'published'::text);


--
-- Name: IX_ads_delete_sweep; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_delete_sweep" ON public.ads USING btree (status, published_at) WHERE ((status)::text = 'archived'::text);


--
-- Name: IX_ads_price_normalized_eur; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_price_normalized_eur" ON public.ads USING btree (price_normalized_eur) WHERE (price_normalized_eur IS NOT NULL);


--
-- Name: IX_ads_pub_listing; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_pub_listing" ON public.ads USING btree (status, category_id, city_id, published_at DESC) WHERE ((status)::text = 'published'::text);


--
-- Name: IX_ads_pub_purpose; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_pub_purpose" ON public.ads USING btree (listing_purpose_id) WHERE ((status)::text = 'published'::text);


--
-- Name: IX_ads_purge_deleted; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_purge_deleted" ON public.ads USING btree (status, deleted_at) WHERE ((status)::text = 'deleted'::text);


--
-- Name: IX_ads_purge_failed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_purge_failed" ON public.ads USING btree (status, moderation_failed_at) WHERE ((status)::text = 'on_moderation_failed'::text);


--
-- Name: IX_ads_rejected_sweep; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_rejected_sweep" ON public.ads USING btree (status, rejected_at) WHERE ((status)::text = 'rejected'::text);


--
-- Name: IX_ads_search_gin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_search_gin" ON public.ads USING gin (search_vector);


--
-- Name: IX_ads_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_user_status" ON public.ads USING btree (user_id, status);


--
-- Name: IX_saved_searches_user_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_saved_searches_user_active" ON public.saved_searches USING btree (user_id, is_active);


--
-- Name: IX_users_erasure_sweep; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_users_erasure_sweep" ON public.users USING btree (consent_revoked_at);


--
-- Name: ad_favorites_ad_id_7bbb8927; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_favorites_ad_id_7bbb8927 ON public.ad_favorites USING btree (ad_id);


--
-- Name: ad_favorites_user_created_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_favorites_user_created_idx ON public.ad_favorites USING btree (user_id, created_at DESC);


--
-- Name: ad_favorites_user_id_2ddb04d4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_favorites_user_id_2ddb04d4 ON public.ad_favorites USING btree (user_id);


--
-- Name: ad_features_ad_id_c4fdf776; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_features_ad_id_c4fdf776 ON public.ad_features USING btree (ad_id);


--
-- Name: ad_features_feature_id_8165d5a0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_features_feature_id_8165d5a0 ON public.ad_features USING btree (feature_id);


--
-- Name: ad_images_ad_id_494b3186; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_images_ad_id_494b3186 ON public.ad_images USING btree (ad_id);


--
-- Name: ad_images_sha256_717d9f97; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_images_sha256_717d9f97 ON public.ad_images USING btree (sha256);


--
-- Name: ad_images_sha256_717d9f97_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_images_sha256_717d9f97_like ON public.ad_images USING btree (sha256 varchar_pattern_ops);


--
-- Name: ad_moderati_base_sc_bb70a8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_moderati_base_sc_bb70a8_idx ON public.ad_moderation_priorities USING btree (base_score);


--
-- Name: ad_moderati_escalat_6731b8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_moderati_escalat_6731b8_idx ON public.ad_moderation_priorities USING btree (escalation_required);


--
-- Name: ad_moderati_priorit_dec75a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ad_moderati_priorit_dec75a_idx ON public.ad_moderation_priorities USING btree (priority_level);


--
-- Name: ads_category_id_8f0a35a1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_category_id_8f0a35a1 ON public.ads USING btree (category_id);


--
-- Name: ads_city_id_c347cd89; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_city_id_c347cd89 ON public.ads USING btree (city_id);


--
-- Name: ads_listing_condition_id_c4e8c1cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_listing_condition_id_c4e8c1cb ON public.ads USING btree (listing_condition_id);


--
-- Name: ads_listing_purpose_id_f48f34be; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_listing_purpose_id_f48f34be ON public.ads USING btree (listing_purpose_id);


--
-- Name: ads_moderated_by_id_3a65327b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_moderated_by_id_3a65327b ON public.ads USING btree (moderated_by_id);


--
-- Name: ads_published_by_id_42d3fb97; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_published_by_id_42d3fb97 ON public.ads USING btree (published_by_id);


--
-- Name: ads_user_id_2d7ee359; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ads_user_id_2d7ee359 ON public.ads USING btree (user_id);


--
-- Name: analytics_events_ad_id_bc186949; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX analytics_events_ad_id_bc186949 ON public.analytics_events USING btree (ad_id);


--
-- Name: analytics_events_source_fee54afe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX analytics_events_source_fee54afe ON public.analytics_events USING btree (source);


--
-- Name: analytics_events_source_fee54afe_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX analytics_events_source_fee54afe_like ON public.analytics_events USING btree (source varchar_pattern_ops);


--
-- Name: analytics_events_user_id_b21e3686; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX analytics_events_user_id_b21e3686 ON public.analytics_events USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: categories_parent_id_fc02df82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX categories_parent_id_fc02df82 ON public.categories USING btree (parent_id);


--
-- Name: categories_slug_9bedfe6b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX categories_slug_9bedfe6b_like ON public.categories USING btree (slug varchar_pattern_ops);


--
-- Name: categories_tree_id_3d4daaa1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX categories_tree_id_3d4daaa1 ON public.categories USING btree (tree_id);


--
-- Name: category_li_categor_191baa_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_li_categor_191baa_idx ON public.category_listing_purposes USING btree (category_id, listing_purpose_id);


--
-- Name: category_li_categor_552b05_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_li_categor_552b05_idx ON public.category_listing_conditions USING btree (category_id, listing_condition_id);


--
-- Name: category_li_categor_c12b58_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_li_categor_c12b58_idx ON public.category_listing_features USING btree (category_id, feature_id);


--
-- Name: category_li_feature_3b48c5_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_li_feature_3b48c5_idx ON public.category_listing_features USING btree (feature_id);


--
-- Name: category_li_listing_072c49_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_li_listing_072c49_idx ON public.category_listing_purposes USING btree (listing_purpose_id);


--
-- Name: category_li_listing_633363_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_li_listing_633363_idx ON public.category_listing_conditions USING btree (listing_condition_id);


--
-- Name: category_listing_conditions_category_id_d85ed7ac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_listing_conditions_category_id_d85ed7ac ON public.category_listing_conditions USING btree (category_id);


--
-- Name: category_listing_conditions_listing_condition_id_1f47face; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_listing_conditions_listing_condition_id_1f47face ON public.category_listing_conditions USING btree (listing_condition_id);


--
-- Name: category_listing_features_category_id_a94aa417; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_listing_features_category_id_a94aa417 ON public.category_listing_features USING btree (category_id);


--
-- Name: category_listing_features_feature_id_af4d317e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_listing_features_feature_id_af4d317e ON public.category_listing_features USING btree (feature_id);


--
-- Name: category_listing_purposes_category_id_b4b15691; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_listing_purposes_category_id_b4b15691 ON public.category_listing_purposes USING btree (category_id);


--
-- Name: category_listing_purposes_listing_purpose_id_4f68d404; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_listing_purposes_listing_purpose_id_4f68d404 ON public.category_listing_purposes USING btree (listing_purpose_id);


--
-- Name: category_paths_category_id_38a05a73; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_paths_category_id_38a05a73 ON public.category_paths USING btree (category_id);


--
-- Name: category_paths_parent_id_54bdf0db; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_paths_parent_id_54bdf0db ON public.category_paths USING btree (parent_id);


--
-- Name: cities_slug_1ca75d72_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cities_slug_1ca75d72_like ON public.cities USING btree (slug varchar_pattern_ops);


--
-- Name: consent_records_user_id_84cae78d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consent_records_user_id_84cae78d ON public.consent_records USING btree (user_id);


--
-- Name: daily_ad_metrics_ad_id_ea146ce7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX daily_ad_metrics_ad_id_ea146ce7 ON public.daily_ad_metrics USING btree (ad_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: exchange_rates_currency_49f1cf9f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exchange_rates_currency_49f1cf9f_like ON public.exchange_rates USING btree (currency varchar_pattern_ops);


--
-- Name: idx_analytics_evt_ts; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_analytics_evt_ts ON public.analytics_events USING btree (event_type, "timestamp");


--
-- Name: idx_daily_metrics_date_views; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_daily_metrics_date_views ON public.daily_ad_metrics USING btree (date, views_count DESC);


--
-- Name: idx_saved_search_notif_sid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_saved_search_notif_sid ON public.saved_search_notifications USING btree (saved_search_id);


--
-- Name: ix_ads_search_gin_bs; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ads_search_gin_bs ON public.ads USING gin (search_vector_bs);


--
-- Name: ix_ads_search_gin_en; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ads_search_gin_en ON public.ads USING gin (search_vector_en);


--
-- Name: ix_ads_search_gin_ru; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ads_search_gin_ru ON public.ads USING gin (search_vector_ru);


--
-- Name: login_tokens_token_hash_18217ec8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX login_tokens_token_hash_18217ec8_like ON public.login_tokens USING btree (token_hash varchar_pattern_ops);


--
-- Name: lookup_groups_code_bc146bb5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX lookup_groups_code_bc146bb5_like ON public.lookup_groups USING btree (code varchar_pattern_ops);


--
-- Name: lookup_items_group_id_fd79a44c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX lookup_items_group_id_fd79a44c ON public.lookup_items USING btree (group_id);


--
-- Name: lookup_items_slug_4d21cf2d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX lookup_items_slug_4d21cf2d_like ON public.lookup_items USING btree (slug varchar_pattern_ops);


--
-- Name: moderation_action_logs_ad_id_893b8987; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX moderation_action_logs_ad_id_893b8987 ON public.moderation_action_logs USING btree (ad_id);


--
-- Name: moderation_action_logs_user_id_5761b02d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX moderation_action_logs_user_id_5761b02d ON public.moderation_action_logs USING btree (user_id);


--
-- Name: moderation_criteria_updated_by_id_0b813e7a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX moderation_criteria_updated_by_id_0b813e7a ON public.moderation_criteria USING btree (updated_by_id);


--
-- Name: popular_searches_query_591d8f7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX popular_searches_query_591d8f7d ON public.popular_searches USING btree (query);


--
-- Name: popular_searches_query_591d8f7d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX popular_searches_query_591d8f7d_like ON public.popular_searches USING btree (query varchar_pattern_ops);


--
-- Name: popular_searches_query_normalized_c335c338; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX popular_searches_query_normalized_c335c338 ON public.popular_searches USING btree (query_normalized);


--
-- Name: popular_searches_query_normalized_c335c338_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX popular_searches_query_normalized_c335c338_like ON public.popular_searches USING btree (query_normalized varchar_pattern_ops);


--
-- Name: popular_searches_source_5986d82c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX popular_searches_source_5986d82c ON public.popular_searches USING btree (source);


--
-- Name: popular_searches_source_5986d82c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX popular_searches_source_5986d82c_like ON public.popular_searches USING btree (source varchar_pattern_ops);


--
-- Name: saved_search_notifications_ad_id_83cbe674; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_search_notifications_ad_id_83cbe674 ON public.saved_search_notifications USING btree (ad_id);


--
-- Name: saved_search_notifications_saved_search_id_51e34407; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_search_notifications_saved_search_id_51e34407 ON public.saved_search_notifications USING btree (saved_search_id);


--
-- Name: saved_searches_category_id_4f5385bd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_searches_category_id_4f5385bd ON public.saved_searches USING btree (category_id);


--
-- Name: saved_searches_city_id_202cf713; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_searches_city_id_202cf713 ON public.saved_searches USING btree (city_id);


--
-- Name: saved_searches_unsubscribe_token_7602c0f4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_searches_unsubscribe_token_7602c0f4_like ON public.saved_searches USING btree (unsubscribe_token varchar_pattern_ops);


--
-- Name: saved_searches_user_id_4b45091f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_searches_user_id_4b45091f ON public.saved_searches USING btree (user_id);


--
-- Name: search_hist_user_id_3ea0ad_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX search_hist_user_id_3ea0ad_idx ON public.search_history USING btree (user_id, created_at DESC);


--
-- Name: search_history_query_normalized_7e015bf2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX search_history_query_normalized_7e015bf2 ON public.search_history USING btree (query_normalized);


--
-- Name: search_history_query_normalized_7e015bf2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX search_history_query_normalized_7e015bf2_like ON public.search_history USING btree (query_normalized varchar_pattern_ops);


--
-- Name: search_history_user_id_b2c466f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX search_history_user_id_b2c466f7 ON public.search_history USING btree (user_id);


--
-- Name: uq_exchange_rate_current_per_currency; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_exchange_rate_current_per_currency ON public.exchange_rates USING btree (currency, is_current) WHERE is_current;


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_preferred_city_id_8835df3d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_preferred_city_id_8835df3d ON public.users USING btree (preferred_city_id);


--
-- Name: users_source_c3429765; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_source_c3429765 ON public.users USING btree (source);


--
-- Name: users_source_c3429765_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_source_c3429765_like ON public.users USING btree (source varchar_pattern_ops);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: ads ads_search_vector_update; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER ads_search_vector_update BEFORE INSERT OR UPDATE ON public.ads FOR EACH ROW EXECUTE FUNCTION public.ads_search_vector_fn();


--
-- Name: categories on_category_name_update; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER on_category_name_update AFTER UPDATE OF name, name_i18n ON public.categories FOR EACH ROW EXECUTE FUNCTION public.categories_name_propagate();


--
-- Name: ad_favorites ad_favorites_ad_id_7bbb8927_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_favorites
    ADD CONSTRAINT ad_favorites_ad_id_7bbb8927_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ad_favorites ad_favorites_user_id_2ddb04d4_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_favorites
    ADD CONSTRAINT ad_favorites_user_id_2ddb04d4_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ad_features ad_features_ad_id_c4fdf776_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_features
    ADD CONSTRAINT ad_features_ad_id_c4fdf776_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ad_features ad_features_feature_id_8165d5a0_fk_lookup_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_features
    ADD CONSTRAINT ad_features_feature_id_8165d5a0_fk_lookup_items_id FOREIGN KEY (feature_id) REFERENCES public.lookup_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ad_images ad_images_ad_id_494b3186_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_images
    ADD CONSTRAINT ad_images_ad_id_494b3186_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ad_moderation_priorities ad_moderation_priorities_ad_id_2d270e0a_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ad_moderation_priorities
    ADD CONSTRAINT ad_moderation_priorities_ad_id_2d270e0a_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_category_id_8f0a35a1_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_category_id_8f0a35a1_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_city_id_c347cd89_fk_cities_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_city_id_c347cd89_fk_cities_id FOREIGN KEY (city_id) REFERENCES public.cities(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_listing_condition_id_c4e8c1cb_fk_lookup_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_listing_condition_id_c4e8c1cb_fk_lookup_items_id FOREIGN KEY (listing_condition_id) REFERENCES public.lookup_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_listing_purpose_id_f48f34be_fk_lookup_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_listing_purpose_id_f48f34be_fk_lookup_items_id FOREIGN KEY (listing_purpose_id) REFERENCES public.lookup_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_moderated_by_id_3a65327b_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_moderated_by_id_3a65327b_fk_users_id FOREIGN KEY (moderated_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_published_by_id_42d3fb97_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_published_by_id_42d3fb97_fk_users_id FOREIGN KEY (published_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ads ads_user_id_2d7ee359_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_user_id_2d7ee359_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: analytics_events analytics_events_ad_id_bc186949_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT analytics_events_ad_id_bc186949_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: analytics_events analytics_events_user_id_b21e3686_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT analytics_events_user_id_b21e3686_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: categories categories_parent_id_fc02df82_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_parent_id_fc02df82_fk_categories_id FOREIGN KEY (parent_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_listing_conditions category_listing_con_category_id_d85ed7ac_fk_categorie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_conditions
    ADD CONSTRAINT category_listing_con_category_id_d85ed7ac_fk_categorie FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_listing_conditions category_listing_con_listing_condition_id_1f47face_fk_lookup_it; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_conditions
    ADD CONSTRAINT category_listing_con_listing_condition_id_1f47face_fk_lookup_it FOREIGN KEY (listing_condition_id) REFERENCES public.lookup_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_listing_features category_listing_fea_feature_id_af4d317e_fk_lookup_it; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_features
    ADD CONSTRAINT category_listing_fea_feature_id_af4d317e_fk_lookup_it FOREIGN KEY (feature_id) REFERENCES public.lookup_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_listing_features category_listing_features_category_id_a94aa417_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_features
    ADD CONSTRAINT category_listing_features_category_id_a94aa417_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_listing_purposes category_listing_pur_listing_purpose_id_4f68d404_fk_lookup_it; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_purposes
    ADD CONSTRAINT category_listing_pur_listing_purpose_id_4f68d404_fk_lookup_it FOREIGN KEY (listing_purpose_id) REFERENCES public.lookup_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_listing_purposes category_listing_purposes_category_id_b4b15691_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_listing_purposes
    ADD CONSTRAINT category_listing_purposes_category_id_b4b15691_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_paths category_paths_category_id_38a05a73_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_paths
    ADD CONSTRAINT category_paths_category_id_38a05a73_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: category_paths category_paths_parent_id_54bdf0db_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_paths
    ADD CONSTRAINT category_paths_parent_id_54bdf0db_fk_categories_id FOREIGN KEY (parent_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consent_records consent_records_user_id_84cae78d_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consent_records
    ADD CONSTRAINT consent_records_user_id_84cae78d_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: daily_ad_metrics daily_ad_metrics_ad_id_ea146ce7_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_ad_metrics
    ADD CONSTRAINT daily_ad_metrics_ad_id_ea146ce7_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lookup_items lookup_items_group_id_fd79a44c_fk_lookup_groups_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lookup_items
    ADD CONSTRAINT lookup_items_group_id_fd79a44c_fk_lookup_groups_id FOREIGN KEY (group_id) REFERENCES public.lookup_groups(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: moderation_action_logs moderation_action_logs_ad_id_893b8987_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderation_action_logs
    ADD CONSTRAINT moderation_action_logs_ad_id_893b8987_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: moderation_action_logs moderation_action_logs_user_id_5761b02d_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderation_action_logs
    ADD CONSTRAINT moderation_action_logs_user_id_5761b02d_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: moderation_criteria moderation_criteria_updated_by_id_0b813e7a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderation_criteria
    ADD CONSTRAINT moderation_criteria_updated_by_id_0b813e7a_fk_users_id FOREIGN KEY (updated_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_search_notifications saved_search_notific_saved_search_id_51e34407_fk_saved_sea; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_search_notifications
    ADD CONSTRAINT saved_search_notific_saved_search_id_51e34407_fk_saved_sea FOREIGN KEY (saved_search_id) REFERENCES public.saved_searches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_search_notifications saved_search_notifications_ad_id_83cbe674_fk_ads_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_search_notifications
    ADD CONSTRAINT saved_search_notifications_ad_id_83cbe674_fk_ads_id FOREIGN KEY (ad_id) REFERENCES public.ads(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_searches saved_searches_category_id_4f5385bd_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_searches
    ADD CONSTRAINT saved_searches_category_id_4f5385bd_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_searches saved_searches_city_id_202cf713_fk_cities_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_searches
    ADD CONSTRAINT saved_searches_city_id_202cf713_fk_cities_id FOREIGN KEY (city_id) REFERENCES public.cities(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_searches saved_searches_user_id_4b45091f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_searches
    ADD CONSTRAINT saved_searches_user_id_4b45091f_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: search_history search_history_user_id_b2c466f7_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_user_id_b2c466f7_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: seller_trust_scores seller_trust_scores_user_id_10e5ff59_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seller_trust_scores
    ADD CONSTRAINT seller_trust_scores_user_id_10e5ff59_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: seller_verifications seller_verifications_user_id_c4c1711e_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seller_verifications
    ADD CONSTRAINT seller_verifications_user_id_c4c1711e_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_preferred_city_id_8835df3d_fk_cities_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_preferred_city_id_8835df3d_fk_cities_id FOREIGN KEY (preferred_city_id) REFERENCES public.cities(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict Ql6CX068oN0YEYgGDta5HBg3PgZnrCcqUte7vnef7xz0sQ174ESYiYzEj1LrUs1

