# Generated by Django 5.2.16 on 2026-08-04 20:52

import apps.lookups.enums
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Russian category name (base storage language)', max_length=200)),
                ('name_i18n', models.JSONField(blank=True, help_text="i18n names: {'ru': <str>, 'bs': <str>, 'en': <str>}; NULL falls back to name", null=True)),
                ('slug', models.SlugField(help_text='URL-friendly category slug', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories hide their ads')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent category for tree structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryListingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_features', to='categories.category')),
                ('feature', models.ForeignKey(limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_FEATURE']}, on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='lookups.lookupitem')),
            ],
            options={
                'verbose_name_plural': 'category listing features',
                'db_table': 'category_listing_features',
                'indexes': [models.Index(fields=['category', 'feature'], name='category_li_categor_c12b58_idx'), models.Index(fields=['feature'], name='category_li_feature_3b48c5_idx')],
                'unique_together': {('category', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='CategoryListingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text="Default purpose for this category; auto-selected when seller doesn't choose explicitly")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_purposes', to='categories.category')),
                ('listing_purpose', models.ForeignKey(limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_PURPOSE']}, on_delete=django.db.models.deletion.CASCADE, related_name='category_purposes', to='lookups.lookupitem')),
            ],
            options={
                'verbose_name_plural': 'category listing purposes',
                'db_table': 'category_listing_purposes',
                'indexes': [models.Index(fields=['category', 'listing_purpose'], name='category_li_categor_191baa_idx'), models.Index(fields=['listing_purpose'], name='category_li_listing_072c49_idx')],
                'unique_together': {('category', 'listing_purpose')},
            },
        ),
        migrations.CreateModel(
            name='CategoryPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Ordering within alternative parent's children")),
                ('is_automatic', models.BooleanField(default=False, help_text='True if created by system rule (e.g. price=0 -> Благотворительность)')),
                ('category', models.ForeignKey(help_text='The leaf/child being navigated to', on_delete=django.db.models.deletion.CASCADE, related_name='alternative_parents', to='categories.category')),
                ('parent', models.ForeignKey(help_text='The alternative parent in the navigation path', on_delete=django.db.models.deletion.CASCADE, related_name='alternative_children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'category paths',
                'db_table': 'category_paths',
                'ordering': ['sort_order'],
                'unique_together': {('category', 'parent')},
            },
        ),
    ]
