# Generated by Django 5.2.16 on 2026-08-25 20:16

import apps.lookups.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryListingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_conditions', to='categories.category')),
                ('listing_condition', models.ForeignKey(limit_choices_to={'group__code': apps.lookups.enums.LookupGroupCode['LISTING_CONDITION']}, on_delete=django.db.models.deletion.CASCADE, related_name='category_conditions', to='lookups.lookupitem')),
            ],
            options={
                'verbose_name_plural': 'category listing conditions',
                'db_table': 'category_listing_conditions',
                'indexes': [models.Index(fields=['category', 'listing_condition'], name='category_li_categor_552b05_idx'), models.Index(fields=['listing_condition'], name='category_li_listing_633363_idx')],
                'unique_together': {('category', 'listing_condition')},
            },
        ),
    ]
