# Generated by Django 5.2.17 on 2026-10-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerverification',
            name='phone_number',
        ),
    ]
